package com.consense.service.drafting;

import com.consense.common.JsonUtils;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.io.*;
import java.util.zip.*;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.*;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.*;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.*;
import org.springframework.test.web.servlet.MockMvc;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/** Agreed real-source upload/preview/generate/body-save/export HTTP interfaces. */
@SpringBootTest(properties={"spring.jpa.hibernate.ddl-auto=create-drop","spring.flyway.enabled=false","consense.llm.enabled=false","consense.ocr.enabled=false","consense.vector.provider=memory"})
@ActiveProfiles("h2") @AutoConfigureMockMvc(print=MockMvcPrint.NONE)
class DraftingNativeLayoutIntegrationTest {
    private static final String RUN=UUID.randomUUID().toString();
    private static final Path EVIDENCE=Paths.get(System.getProperty("consense.acceptance.layoutEvidence","target/native-layout-evidence"),RUN).toAbsolutePath();
    @DynamicPropertySource static void resources(DynamicPropertyRegistry r) {
        r.add("spring.datasource.url",()->"jdbc:h2:mem:native_layout_"+RUN+";MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        r.add("consense.storage-root",()->EVIDENCE.resolve("uploads").toString());
        r.add("consense.drafting.renderer-kind",()->"desktop-x2t");
        r.add("consense.drafting.renderer-executable",()->System.getProperty("consense.acceptance.desktopExecutable",""));
        r.add("consense.drafting.renderer-asset-root",()->System.getProperty("consense.acceptance.desktopAssetRoot",""));
        r.add("consense.drafting.renderer-font-cache",()->System.getProperty("consense.acceptance.desktopFontCache",""));
        r.add("consense.drafting.renderer-work-root",()->System.getProperty("consense.acceptance.layoutWorkRoot",EVIDENCE.resolve("renderer").toString()));
    }
    @Autowired MockMvc mvc;
    @Autowired com.consense.config.ConsenseProperties properties;
    @SuppressWarnings("unchecked") private Map<String,Object> data(String response){return (Map<String,Object>)JsonUtils.readMap(response).get("data");}
    private String project()throws Exception {
        return String.valueOf(data(mvc.perform(post("/api/projects").contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(DraftBusinessRules.map("id","native-layout-"+UUID.randomUUID(),"nameZhHans","TEST ONLY 原生分页","nameEn","TEST ONLY native pagination")))).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString()).get("id"));
    }
    private byte[] source(String key)throws Exception{return Files.readAllBytes(Paths.get(System.getProperty("consense.acceptance.bindingSourceDir"),key+"-source.docx"));}
    private void upload(String id,String key,byte[] bytes)throws Exception {
        mvc.perform(multipart("/api/drafting/{id}/templates/{key}/replace",id,key).file(new MockMultipartFile("file",key+".docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document",bytes))).andExpect(jsonPath("$.data.parsed").value(1));
    }
    private void evidence(String name,byte[] bytes)throws Exception{Files.createDirectories(EVIDENCE);Files.write(EVIDENCE.resolve(name),bytes);}
    @SuppressWarnings("unchecked") @Test void originalNttPreviewStartsEachRegisteredContinuationAfterThePreviousManualFooter()throws Exception {
        String id=project();byte[] original=source("NTT");upload(id,"NTT",original);
        Map<String,Object> sourceBundle=data(mvc.perform(get("/api/drafting/{id}/templates/NTT/bindings",id)).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());
        byte[] pdf=mvc.perform(get("/api/drafting/{id}/templates/NTT/preview.pdf",id).param("sourceSha256",DraftPdfConverter.sha256(original))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();
        evidence("NTT-original.docx",original);evidence("NTT-source.pdf",pdf);evidence("NTT-source-bindings.json",JsonUtils.write(sourceBundle).getBytes(StandardCharsets.UTF_8));
        assertArrayEquals(original,mvc.perform(get("/api/drafting/{id}/templates/NTT/source",id)).andReturn().getResponse().getContentAsByteArray());
        assertNoFooterThenTitle(pdf,"NTT");assertNoBlankOrFurnitureOnly(pdf,"NTT");
        Map<String,Object> located=data(mvc.perform(get("/api/drafting/{id}/templates/NTT/bindings",id)).andExpect(jsonPath("$.data.geometryStatus").value("ready")).andReturn().getResponse().getContentAsString());Map<String,Object> body=((List<Map<String,Object>>)located.get("bindings")).stream().filter(b->Integer.valueOf(546).equals(b.get("sourceParagraphOrdinal"))).findFirst().get();assertNotNull(body.get("geometry"));DraftingDesktopPdfIntegrationTest.assertActualParagraphNear(pdf,body,"The tenderer's attention is drawn");evidence("NTT-located-source-bindings.json",JsonUtils.write(located).getBytes(StandardCharsets.UTF_8));
        @SuppressWarnings("unchecked") Map<String,Object> layout=(Map<String,Object>)sourceBundle.get("nativeLayout");assertEquals("applied",layout.get("status"));assertEquals(sourceBundle.get("docxSha256"),layout.get("docxSha256"));assertEquals(sourceBundle.get("sourceSha256"),layout.get("sourceSha256"));
    }
    @Test void aModifiedSourceEditionIsPreservedAndExplicitlySkipsTheVerifiedLayout()throws Exception {
        String id=project();byte[] original=source("NTT"),modified=modifiedSource(original);assertNotEquals(DraftPdfConverter.sha256(original),DraftPdfConverter.sha256(modified));upload(id,"NTT",modified);
        Map<String,Object> bundle=data(mvc.perform(get("/api/drafting/{id}/templates/NTT/bindings",id)).andExpect(jsonPath("$.data.nativeLayout.status").value("skipped_unverified_source")).andExpect(jsonPath("$.data.nativeLayout.actions").isEmpty()).andReturn().getResponse().getContentAsString());
        assertEquals(DraftPdfConverter.sha256(modified),bundle.get("sourceSha256"));assertArrayEquals(modified,mvc.perform(get("/api/drafting/{id}/templates/NTT/source",id)).andReturn().getResponse().getContentAsByteArray());
        evidence("NTT-modified-source.docx",modified);evidence("NTT-modified-source-bindings.json",JsonUtils.write(bundle).getBytes(StandardCharsets.UTF_8));
    }
    @SuppressWarnings("unchecked")
    @Test void sctOriginalAndSelectedBranchesUseTheUniformRegistryAndRetainAllOtherNativeContent()throws Exception {
        String id=project();for(String key:Arrays.asList("NTT","SCT","SCC"))upload(id,key,source(key));
        Map<String,Object> sourceBundle=data(mvc.perform(get("/api/drafting/{id}/templates/SCT/bindings",id)).andExpect(jsonPath("$.data.nativeLayout.status").value("applied")).andReturn().getResponse().getContentAsString());
        Map<String,Object> sourceLayout=(Map<String,Object>)sourceBundle.get("nativeLayout");List<Map<String,Object>> sourceActions=(List<Map<String,Object>>)sourceLayout.get("actions");assertEquals(25,sourceActions.stream().filter(a->"page_break_before".equals(a.get("action"))).count());assertEquals(5,sourceActions.stream().filter(a->"remove_verified_empty".equals(a.get("action"))).count());assertEquals(sourceBundle.get("docxSha256"),sourceLayout.get("docxSha256"));
        byte[] originalPdf=mvc.perform(get("/api/drafting/{id}/templates/SCT/preview.pdf",id).param("sourceSha256",String.valueOf(sourceBundle.get("sourceSha256")))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();assertNoFooterThenTitle(originalPdf,"SCT");assertNoBlankOrFurnitureOnly(originalPdf,"SCT");try(PDDocument pdf=PDDocument.load(originalPdf)){assertEquals(27,pdf.getNumberOfPages());}
        mvc.perform(put("/api/drafting/{id}/variables/electronicTendering",id).contentType(MediaType.APPLICATION_JSON).content("{\"value\":\"L10Pro\"}")).andExpect(jsonPath("$.code").value(0));
        mvc.perform(put("/api/drafting/{id}/variables/twoEnvelopeTendering",id).contentType(MediaType.APPLICATION_JSON).content("{\"value\":true}")).andExpect(jsonPath("$.code").value(0));
        String kind=properties.getDrafting().getRendererKind();Map<String,byte[]> before=new LinkedHashMap<>();Map<String,Map<String,Object>> after=new LinkedHashMap<>();
        try {properties.getDrafting().setRendererKind("libreoffice");generate(id,"SCT");for(String key:Arrays.asList("NTT","SCT","SCC"))before.put(key,exportWord(id,key));properties.getDrafting().setRendererKind("desktop-x2t");generate(id,"SCT");List<Map<String,Object>> docs=(List<Map<String,Object>>)JsonUtils.readMap(mvc.perform(get("/api/drafting/{id}/documents",id)).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString()).get("data");for(Map<String,Object> doc:docs)after.put(String.valueOf(doc.get("fileKey")),doc);}finally{properties.getDrafting().setRendererKind(kind);}
        for(String key:Arrays.asList("NTT","SCT","SCC")){byte[] actual=exportWord(id,key);assertOnlyRegisteredNativeLayoutDiffers(source(key),before.get(key),actual,(Map<String,Object>)after.get(key).get("nativeLayout"),"NTT".equals(key)?new int[]{410,592}:"SCT".equals(key)?new int[]{878,879,913,914,915}:new int[0]);evidence(key+"-business-baseline.docx",before.get(key));evidence(key+"-registered-business.docx",actual);evidence(key+"-registered-business.json",JsonUtils.write(after.get(key)).getBytes(StandardCharsets.UTF_8));}
        Map<String,Object> generated=after.get("SCT"),layout=(Map<String,Object>)generated.get("nativeLayout");List<Map<String,Object>> actions=(List<Map<String,Object>>)layout.get("actions");assertEquals(20,actions.stream().filter(a->"page_break_before".equals(a.get("action"))&&"APPLIED".equals(a.get("status"))).count());assertEquals(5,actions.stream().filter(a->"page_break_before".equals(a.get("action"))&&"SKIPPED_REMOVED".equals(a.get("status"))).count());
        byte[] resultPdf=mvc.perform(get("/api/drafting/{id}/documents/SCT/preview.pdf",id).param("revisionId",String.valueOf(generated.get("revisionId")))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();assertNoFooterThenTitle(resultPdf,"SCT");assertNoBlankOrFurnitureOnly(resultPdf,"SCT");
        Map<String,Object> located=data(mvc.perform(get("/api/drafting/{id}/documents/SCT/bindings",id)).andExpect(jsonPath("$.data.geometryStatus").value("ready")).andReturn().getResponse().getContentAsString());assertEquals(generated.get("docxSha256"),located.get("docxSha256"));assertEquals(DraftPdfConverter.sha256(resultPdf),located.get("pdfSha256"));
        for(int ordinal:new int[]{256,306,371,531,703}){Map<String,Object> binding=((List<Map<String,Object>>)located.get("bindings")).stream().filter(b->Integer.valueOf(ordinal).equals(b.get("sourceParagraphOrdinal"))).findFirst().get();assertEquals("removed",binding.get("locationStatus"));assertNull(binding.get("geometry"));}
        evidence("SCT-registered-source.pdf",originalPdf);evidence("SCT-registered-result.pdf",resultPdf);evidence("SCT-source-bindings.json",JsonUtils.write(sourceBundle).getBytes(StandardCharsets.UTF_8));evidence("SCT-result-bindings.json",JsonUtils.write(located).getBytes(StandardCharsets.UTF_8));
        Map<String,Object> originalBody=((List<Map<String,Object>>)located.get("bindings")).stream().filter(b->Integer.valueOf(944).equals(b.get("sourceParagraphOrdinal"))).findFirst().get();String bodyId=String.valueOf(originalBody.get("bindingId"));Map<String,Object> block=((List<Map<String,Object>>)generated.get("blocks")).stream().filter(b->bodyId.equals(b.get("bindingId"))).findFirst().get();assertEquals(true,block.get("editable"));String edited=block.get("text")+"\nTEST ONLY\tSCT saved line.";
        Map<String,Object> saved=data(mvc.perform(put("/api/drafting/{id}/documents/SCT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(patch(generated,block,edited,Collections.singletonList("TEST ONLY SCT inserted paragraph."))))).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());assertEquals(edited,((List<Map<String,Object>>)saved.get("blocks")).stream().filter(b->bodyId.equals(b.get("bindingId"))).findFirst().get().get("text"));
        Map<String,Object> savedLayout=(Map<String,Object>)saved.get("nativeLayout");assertEquals(saved.get("docxSha256"),savedLayout.get("docxSha256"));assertEquals(generated.get("docxSha256"),savedLayout.get("compiledDocxSha256"));assertEquals(generated.get("docxSha256"),savedLayout.get("parentDocxSha256"));byte[] savedWord=exportWord(id,"SCT");assertEquals(20,xml(savedWord).getElementsByTagNameNS(NativeDocxComparison.W,"pageBreakBefore").getLength());assertOpaquePartsIdentical(parts(before.get("SCT")),parts(savedWord));
        byte[] savedPdf=mvc.perform(get("/api/drafting/{id}/documents/SCT/preview.pdf",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();assertArrayEquals(savedWord,exportWord(id,"SCT"));assertArrayEquals(savedPdf,mvc.perform(get("/api/drafting/{id}/documents/SCT/export.pdf",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andReturn().getResponse().getContentAsByteArray());
        Map<String,Object> savedBindings=data(mvc.perform(get("/api/drafting/{id}/documents/SCT/bindings",id)).andExpect(jsonPath("$.data.geometryStatus").value("ready")).andReturn().getResponse().getContentAsString());assertEquals(saved.get("docxSha256"),savedBindings.get("docxSha256"));assertEquals(DraftPdfConverter.sha256(savedPdf),savedBindings.get("pdfSha256"));Map<String,Object> currentBody=((List<Map<String,Object>>)savedBindings.get("bindings")).stream().filter(b->bodyId.equals(b.get("bindingId"))).findFirst().get();assertEquals("body_edited",currentBody.get("applicationStatus"));assertEquals(edited,currentBody.get("text"));
        evidence("SCT-body-saved.docx",savedWord);evidence("SCT-body-saved.pdf",savedPdf);evidence("SCT-body-saved.json",JsonUtils.write(saved).getBytes(StandardCharsets.UTF_8));evidence("SCT-body-bindings.json",JsonUtils.write(savedBindings).getBytes(StandardCharsets.UTF_8));
    }
    @SuppressWarnings("unchecked")
    @Test void switchingToDesktopOnlyReportsAnUnrepairedSavedRevisionAndNeverRewritesItsHumanBody()throws Exception {
        String id=project();for(String key:Arrays.asList("NTT","SCT","SCC"))upload(id,key,source(key));String kind=properties.getDrafting().getRendererKind();
        try {
            properties.getDrafting().setRendererKind("libreoffice");Map<String,Object> legacy=generate(id,"NTT");byte[] originalWord=word(id,String.valueOf(legacy.get("revisionId")));assertNull(legacy.get("nativeLayout"));assertEquals(0,xml(originalWord).getElementsByTagNameNS("http://schemas.openxmlformats.org/wordprocessingml/2006/main","pageBreakBefore").getLength());
            Map<String,Object> body=((List<Map<String,Object>>)legacy.get("blocks")).stream().filter(b->Boolean.TRUE.equals(b.get("editable"))&&String.valueOf(b.get("text")).contains("The tenderer's attention is drawn")).findFirst().get();String human=body.get("text")+"\nTEST ONLY pre-policy human body.";
            Map<String,Object> saved=data(mvc.perform(put("/api/drafting/{id}/documents/NTT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(patch(legacy,body,human,null)))).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());byte[] frozen=word(id,String.valueOf(saved.get("revisionId")));properties.getDrafting().setRendererKind("desktop-x2t");
            Map<String,Object> current=((List<Map<String,Object>>)JsonUtils.readMap(mvc.perform(get("/api/drafting/{id}/documents",id)).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString()).get("data")).stream().filter(d->"NTT".equals(d.get("fileKey"))).findFirst().get();
            Map<String,Object> layout=(Map<String,Object>)current.get("nativeLayout");assertEquals("not_applied_to_saved_revision",layout.get("status"));assertEquals(saved.get("revisionId"),current.get("revisionId"));assertEquals(saved.get("docxSha256"),current.get("docxSha256"));assertTrue(String.valueOf(current.get("content")).contains("TEST ONLY pre-policy human body."));assertArrayEquals(frozen,word(id,String.valueOf(saved.get("revisionId"))));
            Map<String,Object> bindings=data(mvc.perform(get("/api/drafting/{id}/documents/NTT/bindings",id)).andExpect(jsonPath("$.data.nativeLayout.status").value("not_applied_to_saved_revision")).andReturn().getResponse().getContentAsString());assertEquals(saved.get("docxSha256"),bindings.get("docxSha256"));
            byte[] pdf=mvc.perform(get("/api/drafting/{id}/documents/NTT/preview.pdf",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();assertArrayEquals(frozen,word(id,String.valueOf(saved.get("revisionId"))));assertEquals(0,xml(frozen).getElementsByTagNameNS("http://schemas.openxmlformats.org/wordprocessingml/2006/main","pageBreakBefore").getLength());
            evidence("NTT-frozen-unrepaired-human.docx",frozen);evidence("NTT-frozen-unrepaired-human.pdf",pdf);evidence("NTT-frozen-unrepaired-info.json",JsonUtils.write(current).getBytes(StandardCharsets.UTF_8));
        } finally {properties.getDrafting().setRendererKind(kind);}
    }
    private static byte[] modifiedSource(byte[] bytes)throws Exception {
        ByteArrayOutputStream out=new ByteArrayOutputStream();try(ZipInputStream in=new ZipInputStream(new ByteArrayInputStream(bytes));ZipOutputStream zip=new ZipOutputStream(out)){ZipEntry entry;while((entry=in.getNextEntry())!=null){byte[] data=in.readAllBytes();if("word/document.xml".equals(entry.getName()))data=new String(data,StandardCharsets.UTF_8).replaceFirst("NOTES TO TENDERERS","NOTES TO TENDERERS TEST ONLY EDITION").getBytes(StandardCharsets.UTF_8);ZipEntry copy=new ZipEntry(entry.getName());copy.setTime(0);zip.putNextEntry(copy);zip.write(data);zip.closeEntry();}}return out.toByteArray();
    }
    @SuppressWarnings("unchecked")
    @Test void generatedNativeLayoutIsProtectedAndPersistsAcrossGuardedBodyRevisionAndSameRevisionExports()throws Exception {
        String id=project();for(String key:Arrays.asList("NTT","SCT","SCC"))upload(id,key,source(key));
        Map<String,Object> sourceBundle=data(mvc.perform(get("/api/drafting/{id}/templates/NTT/bindings",id)).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());
        String originalBinding=String.valueOf(((List<Map<String,Object>>)sourceBundle.get("bindings")).stream().filter(b->Integer.valueOf(546).equals(b.get("sourceParagraphOrdinal"))).findFirst().get().get("bindingId"));
        Map<String,Object> before=generate(id,"NTT");byte[] beforeWord=word(id,String.valueOf(before.get("revisionId")));evidence("NTT-generated.docx",beforeWord);evidence("NTT-generated.json",JsonUtils.write(before).getBytes(StandardCharsets.UTF_8));
        assertEquals(9,xml(beforeWord).getElementsByTagNameNS("http://schemas.openxmlformats.org/wordprocessingml/2006/main","pageBreakBefore").getLength(),"The native exported revision itself carries the registered layout, not a PDF-only copy");
        Map<String,Object> layout=(Map<String,Object>)before.get("nativeLayout");assertNotNull(layout);assertEquals("applied",layout.get("status"));assertEquals(before.get("docxSha256"),layout.get("docxSha256"));assertEquals(before.get("sourceSha256"),layout.get("sourceSha256"));
        List<Map<String,Object>> actions=(List<Map<String,Object>>)layout.get("actions");assertEquals(11,actions.size());
        Map<String,Object> layoutAction=actions.stream().filter(a->"page_break_before".equals(a.get("action"))).findFirst().get();assertNotNull(layoutAction.get("layoutId"));
        Map<String,Object> protectedBlock=((List<Map<String,Object>>)before.get("blocks")).stream().filter(b->layoutAction.get("generatedId").equals(b.get("id"))).findFirst().get();assertEquals(false,protectedBlock.get("editable"));assertEquals("EMPTY_SPAN_UNSUPPORTED",protectedBlock.get("unsupportedReason"));
        mvc.perform(put("/api/drafting/{id}/documents/NTT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(patch(before,protectedBlock,"TEST ONLY forbidden layout edit",null)))).andExpect(jsonPath("$.code").value(4012));assertArrayEquals(beforeWord,word(id,String.valueOf(before.get("revisionId"))));
        Map<String,Object> body=((List<Map<String,Object>>)before.get("blocks")).stream().filter(b->originalBinding.equals(b.get("bindingId"))).findFirst().get();String expected=body.get("text")+"\nTEST ONLY preserved native line.\tTEST ONLY tab.";
        Map<String,Object> request=patch(before,body,expected,Collections.singletonList("TEST ONLY body paragraph before later layout controls."));
        Map<String,Object> saved=data(mvc.perform(put("/api/drafting/{id}/documents/NTT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(request))).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());
        assertNotEquals(before.get("revisionId"),saved.get("revisionId"));assertEquals(expected,((List<Map<String,Object>>)saved.get("blocks")).stream().filter(b->originalBinding.equals(b.get("bindingId"))).findFirst().get().get("text"));
        byte[] savedWord=word(id,String.valueOf(saved.get("revisionId")));assertEquals(saved.get("docxSha256"),DraftPdfConverter.sha256(savedWord));assertEquals(9,xml(savedWord).getElementsByTagNameNS("http://schemas.openxmlformats.org/wordprocessingml/2006/main","pageBreakBefore").getLength());
        Map<String,Object> savedLayout=(Map<String,Object>)saved.get("nativeLayout");assertEquals(saved.get("docxSha256"),savedLayout.get("docxSha256"));assertEquals(before.get("sourceSha256"),savedLayout.get("sourceSha256"));assertEquals(layout.get("profile"),savedLayout.get("profile"));assertEquals(before.get("docxSha256"),savedLayout.get("compiledDocxSha256"));assertEquals(before.get("docxSha256"),savedLayout.get("parentDocxSha256"));
        for(Map<String,Object> action:(List<Map<String,Object>>)savedLayout.get("actions"))if("page_break_before".equals(action.get("action"))&&"APPLIED".equals(action.get("status")))assertTrue(((List<Map<String,Object>>)saved.get("blocks")).stream().anyMatch(b->action.get("generatedId").equals(b.get("id"))&&Boolean.FALSE.equals(b.get("editable"))),"Body insertion must reconcile protected layout control IDs");
        mvc.perform(put("/api/drafting/{id}/documents/NTT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(request))).andExpect(jsonPath("$.code").value(4090));mvc.perform(get("/api/drafting/{id}/documents/NTT/preview.pdf",id).param("revisionId",String.valueOf(before.get("revisionId")))).andExpect(jsonPath("$.code").value(4090));
        byte[] pdf=mvc.perform(get("/api/drafting/{id}/documents/NTT/preview.pdf",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();evidence("NTT-body-saved.docx",savedWord);evidence("NTT-body-saved.pdf",pdf);evidence("NTT-body-saved.json",JsonUtils.write(saved).getBytes(StandardCharsets.UTF_8));assertNoFooterThenTitle(pdf,"NTT");assertNoBlankOrFurnitureOnly(pdf,"NTT");
        Map<String,Object> located=data(mvc.perform(get("/api/drafting/{id}/documents/NTT/bindings",id)).andExpect(jsonPath("$.data.geometryStatus").value("ready")).andReturn().getResponse().getContentAsString());assertEquals(saved.get("revisionId"),located.get("revisionId"));assertEquals(saved.get("docxSha256"),located.get("docxSha256"));assertEquals(DraftPdfConverter.sha256(pdf),located.get("pdfSha256"));Map<String,Object> edited=((List<Map<String,Object>>)located.get("bindings")).stream().filter(b->originalBinding.equals(b.get("bindingId"))).findFirst().get();assertNotNull(edited.get("geometry"));DraftingDesktopPdfIntegrationTest.assertActualParagraphNear(pdf,edited,"The tenderer's attention is drawn");
        assertArrayEquals(pdf,mvc.perform(get("/api/drafting/{id}/documents/NTT/export.pdf",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andReturn().getResponse().getContentAsByteArray());assertArrayEquals(savedWord,word(id,String.valueOf(saved.get("revisionId"))));
        evidence("NTT-body-bindings.json",JsonUtils.write(located).getBytes(StandardCharsets.UTF_8));
        for(String key:Arrays.asList("NTT","SCT","SCC"))assertArrayEquals(source(key),mvc.perform(get("/api/drafting/{id}/templates/{key}/source",id,key)).andReturn().getResponse().getContentAsByteArray());
    }
    @SuppressWarnings("unchecked") private Map<String,Object> generate(String id,String key)throws Exception{return ((List<Map<String,Object>>)JsonUtils.readMap(mvc.perform(post("/api/drafting/{id}/generate",id)).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString()).get("data")).stream().filter(d->key.equals(d.get("fileKey"))).findFirst().get();}
    @SuppressWarnings("unchecked") @Test void fullThirteenBillGenerationDoesNotStrandManualSctFurniture()throws Exception {
        String id=project();for(String key:Arrays.asList("NTT","SCT","SCC"))upload(id,key,source(key));
        byte[] fixture=Files.readAllBytes(Paths.get(System.getProperty("consense.acceptance.fullReferenceInputs")));
        evidence("TEST-ONLY-full13-inputs.json",fixture);
        for(Object raw:JsonUtils.readList(new String(fixture,StandardCharsets.UTF_8),Object.class)){
            Map<String,Object> input=DraftBusinessRules.asMap(raw);
            Object value=input.get("value");String encoded=value instanceof String?(String)value:JsonUtils.write(value);
            mvc.perform(put("/api/drafting/{id}/variables/{key}",id,input.get("key")).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(DraftBusinessRules.map("value",encoded,"note","TEST ONLY full13 pagination fixture; not model or business acceptance.")))).andExpect(jsonPath("$.code").value(0));
        }
        String renderer=properties.getDrafting().getRendererKind();Map<String,byte[]> baseline=new LinkedHashMap<>();
        try{properties.getDrafting().setRendererKind("libreoffice");generate(id,"SCT");for(String key:Arrays.asList("NTT","SCT","SCC"))baseline.put(key,exportWord(id,key));}finally{properties.getDrafting().setRendererKind(renderer);}
        Map<String,Object> generated=generate(id,"SCT");
        for(String key:Arrays.asList("NTT","SCT","SCC")){
            Map<String,Object> originalBundle=data(mvc.perform(get("/api/drafting/{id}/templates/{key}/bindings",id,key)).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());
            byte[] originalPdf=mvc.perform(get("/api/drafting/{id}/templates/{key}/preview.pdf",id,key).param("sourceSha256",DraftPdfConverter.sha256(source(key)))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();
            Map<String,Object> doc=data(mvc.perform(get("/api/drafting/{id}/documents/{key}/bindings",id,key)).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());
            byte[] word=exportWord(id,key),pdf=mvc.perform(get("/api/drafting/{id}/documents/{key}/preview.pdf",id,key).param("revisionId",String.valueOf(doc.get("revisionId")))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();
            assertEquals(doc.get("docxSha256"),DraftPdfConverter.sha256(word));assertOnlyRegisteredNativeLayoutDiffers(source(key),baseline.get(key),word,(Map<String,Object>)doc.get("nativeLayout"),"NTT".equals(key)?new int[]{410,592}:"SCT".equals(key)?new int[]{878,879,913,914,915}:new int[0]);
            evidence(key+"-full13-business-baseline.docx",baseline.get(key));evidence(key+"-full13-generated.docx",word);evidence(key+"-full13-generated.pdf",pdf);evidence(key+"-full13-source.pdf",originalPdf);evidence(key+"-full13-source.json",JsonUtils.write(originalBundle).getBytes(StandardCharsets.UTF_8));evidence(key+"-full13-generated.json",JsonUtils.write(doc).getBytes(StandardCharsets.UTF_8));
            assertNoBlankOrFurnitureOnly(pdf,key);assertNoBlankOrFurnitureOnly(originalPdf,key);if(!"SCC".equals(key)){assertNoFooterThenTitle(pdf,key);assertNoFooterThenTitle(originalPdf,key);}
            assertArrayEquals(source(key),mvc.perform(get("/api/drafting/{id}/templates/{key}/source",id,key)).andReturn().getResponse().getContentAsByteArray());
        }
        Map<String,Object> layout=(Map<String,Object>)generated.get("nativeLayout");List<Map<String,Object>> actions=(List<Map<String,Object>>)layout.get("actions");assertEquals(21,actions.stream().filter(a->"compact_verified_empty_spacing".equals(a.get("action"))&&"APPLIED".equals(a.get("status"))).count());
        for(Map<String,Object> action:actions)if("compact_verified_empty_spacing".equals(action.get("action"))){Map<String,Object> empty=((List<Map<String,Object>>)generated.get("blocks")).stream().filter(b->action.get("generatedId").equals(b.get("id"))).findFirst().get();assertEquals(false,empty.get("editable"));assertEquals("EMPTY_SPAN_UNSUPPORTED",empty.get("unsupportedReason"));mvc.perform(put("/api/drafting/{id}/documents/SCT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(patch(generated,empty,"TEST ONLY forbidden empty-control replacement",null)))).andExpect(jsonPath("$.code").value(4012));}
        Map<String,Object> bundle=data(mvc.perform(get("/api/drafting/{id}/documents/SCT/bindings",id)).andReturn().getResponse().getContentAsString());String bodyId=String.valueOf(((List<Map<String,Object>>)bundle.get("bindings")).stream().filter(b->Integer.valueOf(944).equals(b.get("sourceParagraphOrdinal"))).findFirst().get().get("bindingId"));
        Map<String,Object> block=((List<Map<String,Object>>)generated.get("blocks")).stream().filter(b->bodyId.equals(b.get("bindingId"))).findFirst().get();String edited=block.get("text")+"\nTEST ONLY\tfull13 saved line.";List<String> insert=Arrays.asList("","TEST ONLY full13 inserted paragraph.");Map<String,Object> request=patch(generated,block,edited,insert);
        Map<String,Object> saved=data(mvc.perform(put("/api/drafting/{id}/documents/SCT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(request))).andExpect(jsonPath("$.code").value(0)).andReturn().getResponse().getContentAsString());byte[] savedWord=exportWord(id,"SCT");Map<String,Object> savedLayout=(Map<String,Object>)saved.get("nativeLayout");assertEquals("applied",savedLayout.get("status"));assertEquals(saved.get("docxSha256"),savedLayout.get("docxSha256"));assertEquals(layout.get("compiledDocxSha256"),savedLayout.get("compiledDocxSha256"));assertEquals(layout.get("docxSha256"),savedLayout.get("parentDocxSha256"));
        com.consense.document.DocxTemplateEditor editor=new com.consense.document.DocxTemplateEditor();com.consense.document.DocxTemplateEditor.TemplateIndex index=editor.inspect(baseline.get("SCT"));String start=index.getFeatures().stream().filter(f->bodyId.equals(f.getName())).findFirst().get().getStartId();com.consense.document.DocxTemplateEditor.Paragraph donor=index.paragraph(start.substring(0,start.lastIndexOf("/w:bookmarkStart")));
        byte[] expectedSaved=editor.apply(baseline.get("SCT"),new com.consense.document.DocxTemplateEditor.SourceEditBatch(index.getSourceSha256(),Arrays.asList(com.consense.document.DocxTemplateEditor.Edit.replaceSpan("expected-body",donor,donor.getText().length()-1,donor.getText().length(),".","."+edited.substring(donor.getText().length())),com.consense.document.DocxTemplateEditor.Edit.insertParagraphs("expected-insertion",donor,true,insert,donor)))).getDocxBytes();assertOnlyRegisteredNativeLayoutDiffers(source("SCT"),expectedSaved,savedWord,savedLayout,new int[]{878,879,913,914,915});
        for(Map<String,Object> action:(List<Map<String,Object>>)savedLayout.get("actions"))if("compact_verified_empty_spacing".equals(action.get("action"))){assertEquals("APPLIED",action.get("status"));assertTrue(editor.inspect(savedWord).paragraph(String.valueOf(action.get("generatedId"))).hasCompactEmptyLayoutSpacing());assertTrue(((List<Map<String,Object>>)saved.get("blocks")).stream().anyMatch(b->action.get("generatedId").equals(b.get("id"))&&Boolean.FALSE.equals(b.get("editable"))));}
        assertEquals(edited,((List<Map<String,Object>>)saved.get("blocks")).stream().filter(b->bodyId.equals(b.get("bindingId"))).findFirst().get().get("text"));assertTrue(editor.inspect(savedWord).getMainParagraphs().stream().anyMatch(p->"TEST ONLY full13 inserted paragraph.".equals(p.getText())));
        evidence("SCT-full13-body-baseline.docx",expectedSaved);evidence("SCT-full13-body-saved.docx",savedWord);evidence("SCT-full13-body-saved.json",JsonUtils.write(saved).getBytes(StandardCharsets.UTF_8));
        byte[] savedPdf=mvc.perform(get("/api/drafting/{id}/documents/SCT/preview.pdf",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF)).andReturn().getResponse().getContentAsByteArray();evidence("SCT-full13-body-saved.pdf",savedPdf);assertNoBlankOrFurnitureOnly(savedPdf,"SCT");assertNoFooterThenTitle(savedPdf,"SCT");assertArrayEquals(savedWord,mvc.perform(get("/api/drafting/{id}/documents/SCT/export.docx",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andReturn().getResponse().getContentAsByteArray());assertArrayEquals(savedPdf,mvc.perform(get("/api/drafting/{id}/documents/SCT/export.pdf",id).param("revisionId",String.valueOf(saved.get("revisionId")))).andReturn().getResponse().getContentAsByteArray());mvc.perform(put("/api/drafting/{id}/documents/SCT",id).contentType(MediaType.APPLICATION_JSON).content(JsonUtils.write(request))).andExpect(jsonPath("$.code").value(4090));
    }
    private byte[] word(String id,String revision)throws Exception{return mvc.perform(get("/api/drafting/{id}/documents/NTT/export.docx",id).param("revisionId",revision)).andExpect(status().isOk()).andReturn().getResponse().getContentAsByteArray();}
    @Test void anEditedRegisteredSctEmptyRemainsUnchangedAndSkipsLayout()throws Exception {
        byte[] original=source("SCT");Document document=xml(original);String w=NativeDocxComparison.W;Element p=(Element)document.getElementsByTagNameNS(w,"p").item(197),props=(Element)p.getElementsByTagNameNS(w,"pPr").item(0),spacing=document.createElementNS(w,"w:spacing");spacing.setAttributeNS(w,"w:line","240");spacing.setAttributeNS(w,"w:lineRule","exact");props.insertBefore(spacing,props.getElementsByTagNameNS(w,"ind").item(0));
        ByteArrayOutputStream main=new ByteArrayOutputStream();javax.xml.transform.TransformerFactory.newInstance().newTransformer().transform(new javax.xml.transform.dom.DOMSource(document),new javax.xml.transform.stream.StreamResult(main));Map<String,byte[]> entries=parts(original);entries.put("word/document.xml",main.toByteArray());ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(ZipOutputStream zip=new ZipOutputStream(bytes)){for(Map.Entry<String,byte[]> entry:entries.entrySet()){zip.putNextEntry(new ZipEntry(entry.getKey()));zip.write(entry.getValue());zip.closeEntry();}}byte[] modified=bytes.toByteArray();assertNotEquals(DraftPdfConverter.sha256(original),DraftPdfConverter.sha256(modified));assertOpaquePartsIdentical(parts(original),parts(modified));String id=project();upload(id,"SCT",modified);
        Map<String,Object> bundle=data(mvc.perform(get("/api/drafting/{id}/templates/SCT/bindings",id)).andExpect(jsonPath("$.data.nativeLayout.status").value("skipped_unverified_source")).andExpect(jsonPath("$.data.nativeLayout.actions").isEmpty()).andReturn().getResponse().getContentAsString());assertEquals(DraftPdfConverter.sha256(modified),bundle.get("sourceSha256"));assertArrayEquals(modified,mvc.perform(get("/api/drafting/{id}/templates/SCT/source",id)).andReturn().getResponse().getContentAsByteArray());evidence("SCT-edited-empty-original.docx",modified);evidence("SCT-edited-empty-bundle.json",JsonUtils.write(bundle).getBytes(StandardCharsets.UTF_8));
    }
    /** CT_PPr sequence from the official Open-XML-SDK schema: tabs < spacing < ind/jc/rPr. */
    private static void assertSpacingOrder(Element paragraph){String w=NativeDocxComparison.W;Element props=(Element)paragraph.getElementsByTagNameNS(w,"pPr").item(0);boolean seen=false;for(Node child=props.getFirstChild();child!=null;child=child.getNextSibling())if(child instanceof Element){String name=child.getLocalName();if("spacing".equals(name)){assertFalse(seen);seen=true;}else if("tabs".equals(name))assertFalse(seen,"Spacing must follow original tabs");else if(Set.of("ind","jc","rPr").contains(name))assertTrue(seen,"Spacing must precede the original late paragraph properties");}assertTrue(seen);}
    private static Map<String,Object> patch(Map<String,Object> doc,Map<String,Object> block,String text,List<String> insert){Map<String,Object> edit=DraftBusinessRules.map("id",block.get("id"),"bindingId",block.get("bindingId"),"expectedTextHash",block.get("textHash"),"text",text);if(insert!=null)edit.put("insertAfter",insert);return DraftBusinessRules.map("revisionId",doc.get("revisionId"),"docxSha256",doc.get("docxSha256"),"blocks",Collections.singletonList(edit));}
    private static Document xml(byte[] bytes)throws Exception {try(ZipInputStream in=new ZipInputStream(new ByteArrayInputStream(bytes))){ZipEntry entry;while((entry=in.getNextEntry())!=null)if("word/document.xml".equals(entry.getName())){DocumentBuilderFactory factory=DocumentBuilderFactory.newInstance();factory.setNamespaceAware(true);factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);return factory.newDocumentBuilder().parse(new ByteArrayInputStream(in.readAllBytes()));}}throw new IllegalArgumentException("Missing native document");}
    private byte[] exportWord(String id,String key)throws Exception{return mvc.perform(get("/api/drafting/{id}/documents/{key}/export.docx",id,key)).andExpect(status().isOk()).andReturn().getResponse().getContentAsByteArray();}
    private static Map<String,byte[]> parts(byte[] bytes)throws Exception {Map<String,byte[]> result=new LinkedHashMap<>();try(ZipInputStream in=new ZipInputStream(new ByteArrayInputStream(bytes))){ZipEntry entry;while((entry=in.getNextEntry())!=null)result.put(entry.getName(),in.readAllBytes());}return result;}
    private static void assertOpaquePartsIdentical(Map<String,byte[]> expected,Map<String,byte[]> actual){assertEquals(expected.keySet(),actual.keySet());for(String part:expected.keySet())if(!"word/document.xml".equals(part))assertArrayEquals(expected.get(part),actual.get(part),"Opaque native part: "+part);}
    @SuppressWarnings("unchecked") private static void assertOnlyRegisteredNativeLayoutDiffers(byte[] original,byte[] baseline,byte[] actual,Map<String,Object> layout,int[] allowedEmptyOrdinals)throws Exception {
        Map<String,byte[]> a=parts(baseline),b=parts(actual);assertOpaquePartsIdentical(a,b);
        Document source=xml(original),expected=NativeDocxComparison.withoutAddedBindings(source,xml(baseline)),restored=NativeDocxComparison.withoutAddedBindings(source,xml(actual));String w=NativeDocxComparison.W;Map<String,Map<String,Object>> layoutIds=new HashMap<>();com.consense.document.DocxTemplateEditor editor=new com.consense.document.DocxTemplateEditor();com.consense.document.DocxTemplateEditor.TemplateIndex sourceIndex=editor.inspect(original),actualIndex=editor.inspect(actual);
        if(layout!=null)for(Map<String,Object> action:(List<Map<String,Object>>)layout.get("actions"))if("APPLIED".equals(action.get("status"))&&action.get("layoutId")!=null)assertNull(layoutIds.put(String.valueOf(action.get("layoutId")),action));
        int removed=0;for(Element marker:NativeDocxComparison.elements(restored,"bookmarkStart"))if(layoutIds.containsKey(marker.getAttributeNS(w,"name"))){Element p=(Element)marker.getParentNode();Map<String,Object> action=layoutIds.get(marker.getAttributeNS(w,"name"));assertEquals(0,p.getElementsByTagNameNS(w,"t").getLength());assertEquals(1,p.getElementsByTagNameNS(w,"bookmarkEnd").getLength());Element end=(Element)p.getElementsByTagNameNS(w,"bookmarkEnd").item(0);assertEquals(marker.getAttributeNS(w,"id"),end.getAttributeNS(w,"id"));assertFalse(marker.hasChildNodes());assertFalse(end.hasChildNodes());
            if("page_break_before".equals(action.get("action"))){assertEquals("body",p.getParentNode().getLocalName());assertEquals(1,p.getElementsByTagNameNS(w,"pageBreakBefore").getLength());p.getParentNode().removeChild(p);}else{
                assertEquals("compact_verified_empty_spacing",action.get("action"));com.consense.document.DocxTemplateEditor.Paragraph originalParagraph=sourceIndex.paragraph(String.valueOf(action.get("sourceId")));assertTrue(Arrays.stream(new int[]{146,147,148,149,150,153,154,198,199,200,202,203,204,205,206,207,208,209,212,213,955}).anyMatch(n->n==originalParagraph.getOrdinal()));assertEquals(sourceIndex.anchor(originalParagraph.getId()).getSha256(),action.get("sourceNodeSha256"));assertTrue(actualIndex.paragraph(String.valueOf(action.get("generatedId"))).hasCompactEmptyLayoutSpacing());assertSpacingOrder(p);Element originalP=(Element)source.getElementsByTagNameNS(w,"p").item(originalParagraph.getOrdinal()-1);assertEquals(originalP.getAttributeNS("http://schemas.microsoft.com/office/word/2010/wordml","paraId"),p.getAttributeNS("http://schemas.microsoft.com/office/word/2010/wordml","paraId"));p.removeChild(marker);p.removeChild(end);p.removeChild(p.getElementsByTagNameNS(w,"pPr").item(0));Node originalProps=originalP.getElementsByTagNameNS(w,"pPr").item(0);if(originalProps!=null)p.insertBefore(restored.importNode(originalProps,true),p.getFirstChild());assertTrue(originalP.isEqualNode(p),"Only the recorded spacing and complete added CL pair may change the original empty node");
            }removed++;}assertEquals(layoutIds.size(),removed);
        Set<String> allowedIds=new HashSet<>();for(int ordinal:allowedEmptyOrdinals){Element p=(Element)source.getElementsByTagNameNS(w,"p").item(ordinal-1);assertEquals("body",p.getParentNode().getLocalName());assertEquals(0,p.getElementsByTagNameNS(w,"t").getLength());allowedIds.add(p.getAttributeNS("http://schemas.microsoft.com/office/word/2010/wordml","paraId"));}
        Node expectedBody=expected.getElementsByTagNameNS(w,"body").item(0),actualBody=restored.getElementsByTagNameNS(w,"body").item(0),current=actualBody.getFirstChild();int reinstated=0;
        for(Node node=expectedBody.getFirstChild();node!=null;node=node.getNextSibling())if(current!=null&&node.isEqualNode(current))current=current.getNextSibling();else if(node instanceof Element&&"p".equals(node.getLocalName())&&allowedIds.contains(((Element)node).getAttributeNS("http://schemas.microsoft.com/office/word/2010/wordml","paraId"))){actualBody.insertBefore(restored.importNode(node,true),current);reinstated++;}else fail("Unregistered native content/property change: "+node.getNodeName());
        assertNull(current);assertEquals(allowedEmptyOrdinals.length,reinstated);assertTrue(expected.isEqualNode(restored),"All native fields, controls, paragraphs, tables, styles and attributes must match the baseline business output after reverting only the registered layout");
    }
    private static void assertNoBlankOrFurnitureOnly(byte[] bytes,String key)throws Exception {try(PDDocument pdf=PDDocument.load(bytes)){for(int page=1;page<=pdf.getNumberOfPages();page++){PDFTextStripper strip=new PDFTextStripper();strip.setStartPage(page);strip.setEndPage(page);String substantive=strip.getText(pdf).replaceAll("\\s+","").replace("March2020","").replaceAll("HD\\(QS\\)3C/121/[0-9/]+","").replaceAll("[-–]"+key+"/[0-9]+[-–]","").replaceAll("[^A-Za-z0-9]","");assertFalse(substantive.isEmpty(),"Unexpected blank/furniture-only physical page "+page);}}}
    private static void assertNoFooterThenTitle(byte[] bytes,String key)throws Exception {
        List<String> collisions=new ArrayList<>();try(PDDocument pdf=PDDocument.load(bytes)) {
            for(int page=1;page<=pdf.getNumberOfPages();page++) {
                final Map<Integer,List<TextPosition>> glyphLines=new TreeMap<>();PDFTextStripper strip=new PDFTextStripper(){@Override protected void processTextPosition(TextPosition position){glyphLines.computeIfAbsent(Math.round(position.getYDirAdj()*2),y->new ArrayList<>()).add(position);}};
                strip.setStartPage(page);strip.setEndPage(page);strip.getText(pdf);boolean footer=false;List<String> lines=new ArrayList<>();
                for(List<TextPosition> glyphs:glyphLines.values()){glyphs.sort(Comparator.comparing(TextPosition::getXDirAdj));StringBuilder line=new StringBuilder();for(TextPosition glyph:glyphs)line.append(glyph.getUnicode().replaceAll("\\s+",""));lines.add(line.toString());}
                for(String line:lines){if(line.matches(".*"+key+"/[0-9]+.*"))footer=true;if(footer&&("NTT".equals(key)?line.contains("NOTESTOTENDERERS"):line.contains("SPECIALCONDITIONSOFTENDER")))collisions.add("physical"+page+": "+line);}
            }
        }
        assertTrue(collisions.isEmpty(),"A registered continuation must not follow its preceding manual footer on the same physical page: "+collisions);
    }
}
