package com.consense.service.drafting;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class DraftBusinessRulesTest {
 Map<String,Object> action(Map<String,Object>p,String id){for(Object o:DraftBusinessRules.list(p.get("actions"))){Map<String,Object>a=DraftBusinessRules.asMap(o);if(id.equals(a.get("id")))return a;}throw new AssertionError(id);}
 @Test void emptyAndEverySingleFieldUnknownAreSafe(){Map<String,Object>p=DraftBusinessRules.plan(Collections.emptyMap());assertTrue(DraftBusinessRules.list(p.get("actions")).size()>=107);assertNull(DraftBusinessRules.asMap(p.get("derived")).get("nscApplicable"));for(Map<String,Object>f:DraftBusinessRules.fields()){Map<String,Object>v=new HashMap<>();v.put(String.valueOf(f.get("key")),null);assertDoesNotThrow(()->DraftBusinessRules.plan(v),String.valueOf(f.get("key")));}}
 @Test void inclusiveDoubleConditionAndExplicitNo(){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("foundationIncluded",true,"contractPeriodMonths",39));assertEquals("G1a",action(p,"NTT-10-BOND-REFERENCE").get("value"));p=DraftBusinessRules.plan(DraftBusinessRules.map("foundationIncluded",false));assertEquals("G1",action(p,"NTT-10-BOND-REFERENCE").get("value"));}
 @Test void adoptedThresholdWinsDurationConflictAndIsFlagged(){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("foundationIncluded",true,"periodAtLeast39Months",false,"contractPeriodMonths",40));assertEquals("G1",action(p,"NTT-10-BOND-REFERENCE").get("value"));assertTrue(DraftBusinessRules.list(p.get("unresolved")).stream().anyMatch(o->"InputConflict".equals(DraftBusinessRules.asMap(o).get("kind"))));}
 @Test void repaymentRequiresPositiveWholeNumbersAndInvalidEntryCannotFallBackSilently(){for(Object bad:Arrays.asList(0,-1,1.5,"not a number")){assertNotNull(DraftBusinessRules.invalid("advanceRepaymentMonths",bad));Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("advancePaymentAdopted",true,"advanceRepaymentMonths",bad));assertEquals("pending",action(p,"scc-advance-repayment-standard").get("action"));assertEquals(bad,DraftBusinessRules.asMap(p.get("inputValues")).get("advanceRepaymentMonths"));}}
 @Test void manualTargetKeepsOriginalGroupAssociationAndCanBeReopened(){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("targetOverrides",Collections.singletonList(DraftBusinessRules.map("actionId","NTT-10-BOND-REFERENCE","action","amend","adoptedText","Exact adopted bond wording."))));List<Object>keys=DraftBusinessRules.list(action(p,"NTT-10-BOND-REFERENCE").get("inputKeys"));assertTrue(keys.contains("foundationIncluded"));assertTrue(keys.contains("periodAtLeast39Months"));assertTrue(keys.contains("targetOverrides"));assertEquals(keys.size(),new HashSet<>(keys).size());}
 @Test void pricingMutualExclusionAndMediaIndependent(){for(boolean provisional:new boolean[]{false,true}){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("pricingScheme","BQ_SOR","allBqQuantitiesProvisional",provisional,"electronicTendering","Hardcopy"));assertEquals("not_adopted",action(p,"scc-bq-measurement").get("action"));assertEquals(provisional?"Option B":"Option A",action(p,"scc-mixed-measurement").get("value"));}assertEquals("pending",action(DraftBusinessRules.plan(DraftBusinessRules.map("pricingScheme","BQ")),"scc-bq-measurement").get("action"));}
 @Test void quotationNeedsDesignButNotExecutionAndAdjustmentHasSpecificFoundationTiming(){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("designResponsibilities",Collections.singletonList(DraftBusinessRules.map("component","other","design",true,"execution",false)),"quotationBeforeVariation",true,"foundationDesignSubmittedWithTender",true));assertEquals("retain",action(p,"scc-variation-quotation").get("action"));assertEquals("not_adopted",action(p,"scc-design-adjustment").get("action"));}
 @Test void duplicateAndEmptyTreeIdentityNeverBecomeMultipleTrees(){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("oldValuableTrees",Arrays.asList(DraftBusinessRules.map("serial","T-1"),DraftBusinessRules.map("serial","t-1")),"ovtProjectSpecificText","Wrong multiple-tree text"));assertNull(DraftBusinessRules.asMap(p.get("derived")).get("oldValuableTreeCount"));assertEquals("pending",action(p,"scc-ovt-protection").get("action"));}
 @Test void sourceListsMergeOnlyExactContentAndRetainBothOrigins(){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("domesticBlocks",true,"volumetricPrecastComponents",true,"additionalSubmissions",Collections.singletonList("Submit actual CON8 design."),"pseSubmissions",Collections.singletonList("Submit actual CON8 design.")));List<Object>rows=DraftBusinessRules.list(DraftBusinessRules.asMap(p.get("derived")).get("submissionRequirements"));assertEquals(1,rows.size());assertEquals(2,DraftBusinessRules.list(DraftBusinessRules.asMap(rows.get(0)).get("sources")).size());}
 @Test void finalSubmissionLettersFollowWholeDeletedRows(){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("twoEnvelopeTendering",true,"contractorDesignedFoundations",false,"siteFormationWorks",false,"domesticBlocks",true,"precastFacadePermission",true));assertEquals("SCT5(3)(f)",action(p,"sct-special-payment-submission-reference").get("value"));}
 @Test void legacyBillCandidateIdentityIsStableAndFreeTextPreserved(){DraftBlueprint.InputSpec spec=DraftBlueprint.find("billNos");String rows="[{\"number\":\"9\",\"description\":\"  Exact Formal Description  \"}]";String a=DraftInputRules.normalizeSuggestion(spec,rows);assertEquals(a,DraftInputRules.normalizeSuggestion(spec,rows));assertTrue(a.contains("  Exact Formal Description  "));assertEquals(" 是 ",DraftInputRules.normalize(DraftBlueprint.find("projectArchitectOtherTitle")," 是 "));}
 @Test void incompleteDateAndNegativeRateArePreservedAsInputInvalid(){assertNotNull(DraftBusinessRules.invalid("siteInspectionStartDate","2026-13-01"));Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("twoEnvelopeTendering",true,"photocopyRateUpToA3",-1,"photocopyRateAboveA3",0));assertEquals("pending",action(p,"sct-photocopy-rates").get("action"));assertEquals(-1,DraftBusinessRules.asMap(p.get("inputValues")).get("photocopyRateUpToA3"));}
 @Test void legalFormsHaveDifferentApplicabilityAndUnknownHasManualPath(){String[][]forms={{"partnership","retain","not_adopted"},{"unincorporatedJV","retain","retain"},{"incorporatedJV","not_adopted","retain"},{"other","not_adopted","not_adopted"}};for(String[]f:forms){Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("contractorLegalForm",f[0]));assertEquals(f[1],action(p,"scc-partnership").get("action"));assertEquals(f[2],action(p,"scc-joint-venture").get("action"));}Map<String,Object>p=DraftBusinessRules.plan(DraftBusinessRules.map("partnershipClauseAdopted",true));assertEquals("retain",action(p,"scc-partnership").get("action"));}
}
