package com.consense.service.vetting;

import com.consense.ai.*;
import com.consense.common.JsonUtils;
import com.consense.config.ConsenseProperties;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import java.util.*;
import java.util.stream.Stream;
import static org.junit.jupiter.api.Assertions.*;

class VettingResponsesTransportTest {
    static final String SECRET="FAKE_TEST_CREDENTIAL_ONLY";
    static class Http implements VettingResponsesTransport.WireHttp {
        final List<String> endpoints=new ArrayList<>(),bodies=new ArrayList<>();
        int count=100,status=200;String counterOverride,generation=completed("[]");Runnable counterHook;
        @Override public VettingResponsesTransport.Response post(String endpoint,String body,long timeout,int cap,String auth) {
            assertEquals("Bearer "+SECRET,auth);assertTrue(timeout>0);assertTrue(cap>=1024);endpoints.add(endpoint);bodies.add(body);
            if(endpoint.endsWith("/input_tokens")){if(counterHook!=null)counterHook.run();return new VettingResponsesTransport.Response(status,counterOverride==null?"{\"object\":\"response.input_tokens\",\"input_tokens\":"+count+"}":counterOverride);}
            return new VettingResponsesTransport.Response(status,generation);
        }
    }
    static ConsenseProperties props(){ConsenseProperties p=new ConsenseProperties();ConsenseProperties.Responses r=p.getVetting().getResponses();r.setEnabled(true);r.setApiKey(SECRET);r.setConfiguredContextTokens(50000);r.setSafetyMarginTokens(500);r.setEstimatePolicy(VettingResponsesTransport.POLICY);return p;}
    static JsonNode schema(){return JsonUtils.parse("{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"additionalProperties\":false}}");}
    static VettingInputBudget.Input input(VettingResponsesTransport t){return t.input("Synthetic instruction unchanged.","Native cells ['', 'Room | East 😀 中文']",schema(),VettingCorpus.hash("synthetic source"));}
    static String completed(String text){ObjectNode r=JsonUtils.mapper().createObjectNode();r.put("object","response");r.put("model","MiniMax-M3");r.put("status","completed");ObjectNode m=r.putArray("output").addObject();m.put("type","message");m.put("role","assistant");m.put("status","completed");m.putArray("content").addObject().put("type","output_text").put("text",text);r.put("output_text",text);return JsonUtils.write(r);}
    private List<Map> complete(VettingResponsesTransport t,VettingInputBudget.Input in,VettingInputBudget.Result budget){return t.complete(in,budget,"Synthetic instruction unchanged.","Native cells ['', 'Room | East 😀 中文']",schema(),Map.class,new ArrayList<>(),new LinkedHashMap<>());}

    @Test void sharedCodecCountsExactInstructionsUserSchemaAndDoesNotClaimHiddenTemplate() {
        Http h=new Http();ConsenseProperties p=props();VettingResponsesTransport t=new VettingResponsesTransport(p,h);VettingInputBudget.Input in=input(t);VettingResponsesTransport.PreparedRequest prepared=t.prepare(in);
        JsonNode g=JsonUtils.parse(prepared.getGenerationJson()),c=JsonUtils.parse(prepared.getCounterJson());assertEquals(new HashSet<>(Arrays.asList("model","instructions","input","reasoning")),keys(c));for(String k:keys(c))assertEquals(g.get(k),c.get(k));assertEquals(in.getMessages().get(0).getContent(),c.get("instructions").textValue());assertEquals(in.getMessages().get(1).getContent(),c.get("input").get(0).get("content").textValue());assertEquals("high",c.path("reasoning").path("effort").asText());assertEquals(0.2,g.get("temperature").doubleValue());assertEquals(16384,g.get("max_output_tokens").intValue());assertFalse(g.get("stream").booleanValue());assertFalse(g.has("max_tokens")||g.has("n")||g.has("thinking")||g.has("reasoning_split"));assertFalse(JsonUtils.write(in).contains(SECRET));
        VettingInputBudget.Result budget=VettingInputBudget.check(in,t::observe);assertEquals("provider_estimated_fit",budget.getStatus());assertTrue(budget.isExtraDispatchPermitted());assertFalse(budget.getObservation().isCompleteChatTemplateAndSchemaObserved());assertNull(budget.getObservation().getTokenizerIdentitySha256());assertTrue(budget.getObservation().getProviderEstimate().isResponseModelUnavailable());assertEquals("request_declared",budget.getObservation().getProviderEstimate().getModelIdentityScope());assertTrue(complete(t,in,budget).isEmpty());assertEquals(Arrays.asList(prepared.getCounterEndpoint(),prepared.getGenerationEndpoint()),h.endpoints);assertEquals(prepared.getCounterJson(),h.bodies.get(0));assertEquals(prepared.getGenerationJson(),h.bodies.get(1));
    }
    @Test void defaultLocalInputAndObservationBytesRetainOldShape() {
        VettingInputBudget.Input in=VettingInputBudget.input("openai","fixture-model",VettingCorpus.hash("safe config"),"system","user",schema(),100,VettingCorpus.hash("source"));
        assertFalse(JsonUtils.write(in).contains("\"wire\""));assertFalse(JsonUtils.write(new VettingInputBudget.Observation()).contains("providerEstimate"));assertNull(in.getWire());assertFalse(new ConsenseProperties().getVetting().getResponses().isEnabled());
        assertEquals("observed_tokens",VettingInputBudget.check(in,VettingInputBudgetTest::fixtureObservation).getStatus());
    }
    @Test void savedGatewayReplayDoesNotDuplicateSchemaOrChangeNativeText() {
        Http h=new Http();VettingResponsesTransport t=new VettingResponsesTransport(props(),h);VettingInputBudget.Input in=input(t);
        VettingInputBudget.Input rebound=t.inputFromGateway(in.getMessages().get(0).getContent(),in.getMessages().get(1).getContent(),schema(),in.getSourceSnapshotSha256());assertEquals(JsonUtils.write(in),JsonUtils.write(rebound));assertTrue(h.endpoints.isEmpty());assertThrows(Exception.class,()->t.inputFromGateway("unenveloped",in.getMessages().get(1).getContent(),schema(),in.getSourceSnapshotSha256()));
    }
    @Test void noPolicyOrContextOrCredentialCannotAuthorizeEvenGlobal() {
        for(int variant=0;variant<4;variant++){Http h=new Http();ConsenseProperties p=props();if(variant==0)p.getVetting().getResponses().setEstimatePolicy(null);if(variant==1)p.getVetting().getResponses().setConfiguredContextTokens(0);if(variant==2)p.getVetting().getResponses().setApiKey("");if(variant==3)p.getVetting().getResponses().setEstimatePolicy("offline_plan");VettingResponsesTransport t=new VettingResponsesTransport(p,h);VettingInputBudget.Input in=input(t);VettingInputBudget.Result b=VettingInputBudget.check(in,t::observe);assertEquals("budget_unknown",b.getStatus());assertFalse(b.isExtraDispatchPermitted());assertTrue(h.endpoints.isEmpty());assertThrows(Exception.class,()->complete(t,in,b));assertTrue(h.endpoints.isEmpty());}
    }
    @Test void explicitAbsoluteMarginBoundaryAndOverBudgetAreSeparateFromPrecision() {
        Http h=new Http();ConsenseProperties p=props();VettingResponsesTransport t=new VettingResponsesTransport(p,h);VettingInputBudget.Input in=input(t);h.count=50000-16384-500;assertEquals("provider_estimated_fit",VettingInputBudget.check(in,t::observe).getStatus());h.count++;VettingInputBudget.Result over=VettingInputBudget.check(in,t::observe);assertEquals("over_budget",over.getStatus());assertFalse(over.isExtraDispatchPermitted());assertThrows(Exception.class,()->complete(t,in,over));assertTrue(h.endpoints.stream().allMatch(s->s.endsWith("/input_tokens")));
    }
    static Stream<String> badCounters(){return Stream.of("{}","[]","{\"object\":\"wrong\",\"input_tokens\":100}","{\"object\":\"response.input_tokens\",\"input_tokens\":\"100\"}","{\"object\":\"response.input_tokens\",\"input_tokens\":0}","{\"object\":\"response.input_tokens\",\"input_tokens\":-1}","{\"object\":\"response.input_tokens\",\"input_tokens\":1.5}","{\"object\":\"response.input_tokens\",\"input_tokens\":9223372036854775808}","{\"object\":\"response.input_tokens\",\"input_tokens\":99999,\"input_tokens\":100}","{\"object\":\"response.input_tokens\",\"input_tokens\":100}{}","{\"object\":\"response.input_tokens\",\"input_tokens\":100,\"model\":\"wrong\"}","{\"object\":\"response.input_tokens\",\"input_tokens\":100,\"error\":\"failed\"}");}
    @ParameterizedTest @MethodSource("badCounters") void malformedCounterAlwaysUnknownAndNoGeneration(String raw){Http h=new Http();h.counterOverride=raw;VettingResponsesTransport t=new VettingResponsesTransport(props(),h);VettingInputBudget.Input in=input(t);VettingInputBudget.Result b=VettingInputBudget.check(in,t::observe);assertEquals("budget_unknown",b.getStatus());assertFalse(b.isExtraDispatchPermitted());assertThrows(Exception.class,()->complete(t,in,b));assertEquals(1,h.endpoints.size());}
    @Test void counterStatusExceptionOversizeAndProfileDriftRemainUnknownWithoutRetry() {
        for(int variant=0;variant<4;variant++){Http h=new Http();ConsenseProperties p=props();if(variant==0)h.status=403;if(variant==1)h.counterHook=()->{throw new IllegalStateException(SECRET);};if(variant==2){p.getVetting().getResponses().setCounterMaxResponseBytes(1024);h.counterOverride=String.join("",Collections.nCopies(1025,"x"));}if(variant==3)h.counterHook=()->p.getVetting().getResponses().setSafetyMarginTokens(501);VettingResponsesTransport t=new VettingResponsesTransport(p,h);VettingInputBudget.Result b=VettingInputBudget.check(input(t),t::observe);assertEquals("budget_unknown",b.getStatus());assertFalse(b.getReason().contains(SECRET));assertEquals(1,h.endpoints.size());}
    }
    @Test void entityProfileSchemaSourceAndWireMutationFailBeforeHttp() {
        for(int variant=0;variant<7;variant++){Http h=new Http();ConsenseProperties p=props();VettingResponsesTransport t=new VettingResponsesTransport(p,h);VettingInputBudget.Input in=input(t);if(variant==0)in.setProvider("openai");if(variant==1)in.setModel("different-model");if(variant==2)in.setSourceSnapshotSha256(VettingCorpus.hash("changed source"));if(variant==3)in.getSchema().deepCopy();if(variant==3)((ObjectNode)in.getSchema()).put("maxItems",2);if(variant==4)in.getWire().setCounterProjectionSha256(VettingCorpus.hash("changed projection"));if(variant==5)p.getVetting().getResponses().setSafetyMarginTokens(501);if(variant==6)in.setMessages(Arrays.asList(LlmClient.ChatTurn.system("changed"),LlmClient.ChatTurn.user("changed")));assertEquals("budget_unknown",VettingInputBudget.check(in,t::observe).getStatus());assertTrue(h.endpoints.isEmpty());}
    }
    @Test void preparedArtifactsDefensiveCopiesAndPublicIdentityExcludeCredential() {
        Http h=new Http();ConsenseProperties p=props();VettingResponsesTransport t=new VettingResponsesTransport(p,h);VettingInputBudget.Input in=input(t);VettingResponsesTransport.PreparedRequest prepared=t.prepare(in);String before=prepared.getGenerationJson();prepared.getWire().setGenerationEntitySha256("wrong");assertEquals(before,prepared.getGenerationJson());assertEquals(in.getWire().getGenerationEntitySha256(),prepared.getWire().getGenerationEntitySha256());String identity=in.getProviderConfigurationSha256();p.getVetting().getResponses().setApiKey("OTHER_FAKE_CREDENTIAL");assertEquals(identity,input(t).getProviderConfigurationSha256());assertFalse(prepared.getInputJson().contains(SECRET));
    }
    @Test void observationWireSpoofCannotBecomeLocalExactAndRemoteMissingIdentityFailsClosed() {
        Http h=new Http();VettingResponsesTransport t=new VettingResponsesTransport(props(),h);VettingInputBudget.Input in=input(t);VettingInputBudget.Observation o=t.observe(in);o.setCompleteChatTemplateAndSchemaObserved(true);assertEquals("budget_unknown",VettingInputBudget.check(in,x->o).getStatus());o.setCompleteChatTemplateAndSchemaObserved(false);o.getProviderEstimate().setGenerationEntitySha256(VettingCorpus.hash("other"));assertEquals("budget_unknown",VettingInputBudget.check(in,x->o).getStatus());VettingInputBudget.Input local=VettingInputBudget.input("openai","MiniMax-M3","system","user",schema(),100,VettingCorpus.hash("source"));assertEquals("budget_unknown",VettingInputBudget.check(local,x->t.observe(in)).getStatus());
    }
    @Test void postCountPromptOrProfileChangeNeverGenerates() {
        Http h=new Http();ConsenseProperties p=props();VettingResponsesTransport t=new VettingResponsesTransport(p,h);VettingInputBudget.Input in=input(t);VettingInputBudget.Result b=VettingInputBudget.check(in,t::observe);assertThrows(Exception.class,()->t.complete(in,b,"changed system","Native cells ['', 'Room | East 😀 中文']",schema(),Map.class,new ArrayList<>(),null));p.getVetting().getResponses().setConfiguredContextTokens(50001);assertThrows(Exception.class,()->complete(t,in,b));assertEquals(1,h.endpoints.size());
    }
    static Stream<String> incompleteResponses(){return Stream.of("{\"object\":\"response\",\"model\":\"MiniMax-M3\",\"status\":\"incomplete\",\"incomplete_details\":{\"reason\":\"max_output_tokens\"},\"output_text\":\"[]\",\"output\":[]}","{\"object\":\"response\",\"model\":\"MiniMax-M3\",\"status\":\"completed\",\"output_text\":\"[]\",\"output\":[]}","{\"object\":\"response\",\"model\":\"MiniMax-M3\",\"status\":\"failed\",\"error\":{\"message\":\"FAKE_TEST_CREDENTIAL_ONLY\"}}",completed("[]").replace("\"model\":\"MiniMax-M3\"","\"model\":\"other\""),completed("[]").replace("\"status\":\"completed\"","\"status\":\"unknown\""),completed("[]").replace("\"type\":\"output_text\"","\"type\":\"refusal\""),completed("[]").replace("\"type\":\"message\"","\"type\":\"function_call\""),completed("[]").replace("\"output_text\":\"[]\"","\"output_text\":\"changed\""),completed("[]").replace("\"status\":\"completed\"","\"status\":\"completed\",\"status\":\"completed\""),completed("[]")+"{}",completed("[]").replace("\"object\":\"response\"","\"object\":\"response\",\"base_resp\":{\"status_code\":123}"));}
    @ParameterizedTest @MethodSource("incompleteResponses") void typedGenerationTerminalFailuresNeverParseAsEmpty(String raw){Http h=new Http();h.generation=raw;VettingResponsesTransport t=new VettingResponsesTransport(props(),h);VettingInputBudget.Input in=input(t);VettingInputBudget.Result b=VettingInputBudget.check(in,t::observe);IncompleteModelResponseException e=assertThrows(IncompleteModelResponseException.class,()->complete(t,in,b));assertNotEquals(IncompleteModelResponseException.FailureKind.UNKNOWN,e.getFailureKind());assertFalse(e.getRawResponse().contains(SECRET));assertEquals(2,h.endpoints.size());}
    @Test void outputBudgetKindAndFencedJsonAreKeptDistinct() {
        Http h=new Http();h.generation="{\"object\":\"response\",\"model\":\"MiniMax-M3\",\"status\":\"incomplete\",\"incomplete_details\":{\"reason\":\"max_output_tokens\"},\"output\":[]}";VettingResponsesTransport t=new VettingResponsesTransport(props(),h);VettingInputBudget.Input in=input(t);VettingInputBudget.Result b=VettingInputBudget.check(in,t::observe);assertEquals(IncompleteModelResponseException.FailureKind.OUTPUT_BUDGET_EXHAUSTED,assertThrows(IncompleteModelResponseException.class,()->complete(t,in,b)).getFailureKind());h.generation=completed("```json\n[]\n```");assertThrows(StructuredOutputValidationException.class,()->complete(t,in,b));assertEquals(3,h.endpoints.size());
    }
    @Test void falseLocalHashesAndChangedReserveAreNotAcceptedAsProviderEstimate() {
        for(int v=0;v<4;v++){Http h=new Http();VettingResponsesTransport t=new VettingResponsesTransport(props(),h);VettingInputBudget.Input in=input(t);VettingInputBudget.Observation o=t.observe(in);if(v==0)o.setTokenizerIdentitySha256(VettingCorpus.hash("fake opaque tokenizer"));if(v==1)o.setChatTemplateIdentitySha256(VettingCorpus.hash("fake opaque template"));if(v==2)o.getProviderEstimate().setContextPolicySha256(null);if(v==3)o.setOutputReserveTokens(16383);assertEquals("budget_unknown",VettingInputBudget.check(in,x->o).getStatus());}
    }
    private static Set<String> keys(JsonNode n){Set<String> keys=new HashSet<>();n.fieldNames().forEachRemaining(keys::add);return keys;}
}
