package com.consense.service.drafting;

import com.consense.common.JsonUtils;
import com.consense.domain.DraftVariable;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.time.LocalDate;
import java.util.*;

/** Pure, versioned drafting decisions. Facts, adoption and source mapping are separate. */
public final class DraftBusinessRules {
 private DraftBusinessRules() { }
 public static final String RULE_VERSION="drafting-20261006.8-docx";
 private static final ObjectMapper JSON=new ObjectMapper();
 private static final Map<String,Object> RAW=load();
 private static Map<String,Object> load() {try(InputStream in=DraftBusinessRules.class.getResourceAsStream("/drafting/input-catalog.json")){return JSON.readValue(in,new TypeReference<LinkedHashMap<String,Object>>(){});}catch(Exception ex){throw new IllegalStateException("Missing versioned drafting catalog",ex);}}
 public static Map<String,Object> catalog() {return map("ruleVersion",RULE_VERSION,"groups",RAW.get("groups"),"systemFields",RAW.get("systemFields"));}
 public static String standardParagraph(String document,int paragraph){return s(asMap(asMap(RAW.get("sourceDocuments")).get(document)).get(String.valueOf(paragraph)));}
 @SuppressWarnings("unchecked") public static List<Map<String,Object>> fields() {List<Map<String,Object>> result=new ArrayList<>();for(Object o:list(RAW.get("groups"))) result.addAll((List<Map<String,Object>>)((Map<String,Object>)o).get("fields"));return result;}
 public static Map<String,Object> decode(List<DraftVariable> variables) {Map<String,Object> values=new LinkedHashMap<>();for(DraftVariable v:variables){if(v.getValueText()==null||v.getValueText().trim().isEmpty())continue;values.put(v.getVarKey(),parse(v.getValueText()));}return values;}
 public static Object parse(String text) {try{return JSON.readValue(text,Object.class);}catch(Exception ex){return text;}}
 public static Map<String,Object> plan(List<DraftVariable> variables,Map<String,String> templates) {Map<String,Object> p=plan(decode(variables));p.put("templateKeys",templates==null?Collections.emptySet():templates.keySet());return p;}
 public static Map<String,Object> plan(Map<String,Object> input) {
  Map<String,Object> values=new LinkedHashMap<>();if(input!=null)values.putAll(input);
  if(values.containsKey("targetEdits")&&!values.containsKey("targetOverrides"))values.put("targetOverrides",values.get("targetEdits"));
  Map<String,Object> effective=new LinkedHashMap<>(values);List<Map<String,Object>> unresolved=new ArrayList<>();
  // An adopted threshold wins. Exact duration only supplies an unanswered threshold.
  {Double months=number(values.get("contractPeriodMonths"));Boolean threshold=truth(values.get("periodAtLeast39Months"));if(months!=null&&months>=0){if(threshold==null)effective.put("periodAtLeast39Months",months>=39);else if(threshold!=(months>=39))unresolved.add(issue("input-duration-threshold","InputConflict",null,null,Arrays.asList("contractPeriodMonths","periodAtLeast39Months"),"The adopted 39-month threshold conflicts with the stated duration. The adopted threshold is retained for this draft; review the evidence."));}}
  for(Map<String,Object> f:fields()){
   String key=s(f.get("key"));Boolean applicable=condition(f.get("condition"),effective);
   if(Boolean.FALSE.equals(applicable)){effective.remove(key);continue;}
   String invalid=invalid(key,values.get(key));if(invalid!=null){effective.remove(key);unresolved.add(issue("input-"+key,"InputInvalid",null,null,Collections.singletonList(key),invalid));}
   else if(!Boolean.TRUE.equals(f.get("optional"))&&!answered(effective.get(key)))unresolved.add(issue("input-"+key,applicable==null?"PrerequisiteUnknown":"InputMissing",null,null,Collections.singletonList(key),"Enter or adopt the value for this draft; unknown is not No."));
  }
  if(values.get("contractTitle") instanceof Map){for(String part:Arrays.asList("number","title"))if(!answered(asMap(values.get("contractTitle")).get(part)))unresolved.add(issue("input-contractTitle-"+part,"InputMissing",null,null,Collections.singletonList("contractTitle"),"Complete the missing contract "+part+"; the adopted sibling value is preserved."));}
  String dates=datesIssue(values);if(dates!=null){effective.remove("siteInspectionStartDate");effective.remove("siteInspectionEndDate");unresolved.add(issue("input-siteInspectionDates","InputInvalid","SCT","SCT8",Arrays.asList("siteInspectionStartDate","siteInspectionEndDate"),dates));}
  List<Map<String,Object>> actions=new ArrayList<>();for(Object o:list(RAW.get("actionCatalog"))){Map<String,Object> a=new LinkedHashMap<>(asMap(o));a.put("action","pending");a.put("inputKeys",Collections.emptyList());actions.add(a);}
  Context c=new Context(effective,actions);baseRules(c);additionalRules(c);for(String key:Arrays.asList("advanceRepaymentMonths","advanceRepaymentFirstCertificate"))if(invalid(key,values.get(key))!=null)c.set("scc-advance-repayment-standard","pending",null,"Review the invalid adopted repayment parameter; the original standard wording remains.","请复核无效的采用还款参数；保留原标准条文。",key);adoptTargetEdits(c,values.get("targetOverrides"));references(c);adoptTargetEdits(c,values.get("targetOverrides"));
  for(Object o:list(values.get("targetOverrides"))){Map<String,Object> edit=asMap(o);String id=s(edit.get("actionId"));String problem=DraftTargetDecisions.problem(c.find(id),edit);if(problem!=null)unresolved.add(issue("override-"+id,"InvalidOverride",s(edit.get("document")),s(edit.get("clause")),Collections.singletonList("targetOverrides"),problem));}
  for(Map<String,Object> a:actions)if("pending".equals(a.get("action")))unresolved.add(map("id",a.get("id"),"kind",a.getOrDefault("pendingKind","BusinessValue"),"document",a.get("document"),"clause",a.get("clause"),"inputKeys",a.get("inputKeys"),"message",a.get("detail")));
  return map("ruleVersion",RULE_VERSION,"inputValues",values,"effectiveValues",effective,"derived",c.derived,"actions",actions,"unresolved",unresolved);
 }
 public static Boolean truth(Object v){if(v instanceof Boolean)return(Boolean)v;if(v==null)return null;String t=s(v).trim();if(Arrays.asList("true","Yes","yes","是").contains(t))return true;if(Arrays.asList("false","No","no","否").contains(t))return false;return null;}
 public static boolean answered(Object v){if(v==null)return false;if(v instanceof String)return !s(v).trim().isEmpty()&&!Arrays.asList("unknown","待确定","待確認","To be confirmed").contains(s(v).trim());return true;}
 static Double number(Object v){try{if(!answered(v))return null;double n=Double.parseDouble(s(v));return Double.isFinite(n)?n:null;}catch(RuntimeException ex){return null;}}
 static Boolean and(Boolean... vals){boolean unknown=false;for(Boolean v:vals){if(Boolean.FALSE.equals(v))return false;if(v==null)unknown=true;}return unknown?null:Boolean.TRUE;}
 static String action(Boolean b,String no){return b==null?"pending":b?"retain":no;}
 @SuppressWarnings("unchecked") public static Boolean condition(Object rule,Map<String,Object> values){if(!(rule instanceof Map))return true;Boolean result=true;for(Object o:list(asMap(rule).get("all"))){Map<String,Object> t=asMap(o);Object actual=values.get(s(t.get("field"))), expected=t.get("value");String op=s(t.get("operator"));Boolean term;
  if("unknown".equals(op))term=!answered(actual);
  else if(!answered(actual))term=null;
  else if("eq".equals(op))term=expected instanceof Boolean?Objects.equals(truth(actual),expected):Objects.equals(actual,expected);
  else if("in".equals(op))term=list(expected).contains(actual);
  else if("countGt".equals(op))term=invalid("oldValuableTrees",actual)!=null?null:list(actual).size()>((Number)expected).intValue();
  else if("includesComponent".equals(op)){term=false;for(Object row:list(actual))if(Objects.equals(asMap(row).get("component"),expected))term=true;}
  else term=null;result=and(result,term);
 }return result;}
 static String invalid(String key,Object value){if(!answered(value))return null;
  if(Arrays.asList("advanceRepaymentMonths","advanceRepaymentFirstCertificate").contains(key)){Double n=number(value);if(n==null||n<=0||n!=Math.rint(n))return "A positive integer is required for the repayment period and first certificate number.";}
  if(Arrays.asList("siteInspectionStartDate","siteInspectionEndDate").contains(key)){try{LocalDate.parse(s(value));}catch(RuntimeException ex){return "Use a valid ISO date.";}}
  if(Arrays.asList("photocopyRateUpToA3","photocopyRateAboveA3","contractPeriodMonths","advanceRepaymentMonths","advanceRepaymentFirstCertificate").contains(key)){Double n=number(value);if(n==null||n<0)return "A finite non-negative number is required; the entered value is retained for review.";}
  if("oldValuableTrees".equals(key)){if(!(value instanceof List))return "Tree identities must be a list.";Set<String> seen=new HashSet<>();for(Object o:list(value)){String serial=o instanceof String?s(o):s(asMap(o).get("serial"));if(serial.trim().isEmpty())return "Complete every tree serial number before selecting single or multiple-tree handling.";if(!seen.add(serial.trim().toUpperCase(Locale.ROOT)))return "Duplicate tree serial numbers: verify identities; all entered rows are retained.";}}
  if("billNos".equals(key)){if(!(value instanceof List))return "Bill / Schedule rows must be a list.";Set<String> seen=new HashSet<>();for(Object o:list(value)){Map<String,Object> r=asMap(o);if(!answered(r.get("number"))||!answered(r.get("description")))return "Complete each Bill / Schedule number and exact description.";String identity=s(r.get("type"))+":"+s(r.get("number")).trim().toLowerCase(Locale.ROOT);if(!seen.add(identity))return "Duplicate numbers within the same pricing-document type require review.";}}
  if("sections".equals(key)){if(!(value instanceof List))return "Sections must be a list.";Set<String> seen=new HashSet<>();for(Object o:list(value)){Map<String,Object> r=asMap(o);if(!answered(r.get("designation"))||!answered(r.get("workTypes"))||list(r.get("workTypes")).isEmpty())return "Each Section requires its designation and actual Works types.";if(!seen.add(s(r.get("designation")).trim().toUpperCase(Locale.ROOT)))return "Duplicate Section designations require review.";}}
  return DraftInputRules.structuredIssue(key,value);
 }
 static String datesIssue(Map<String,Object> v){if(!answered(v.get("siteInspectionStartDate"))||!answered(v.get("siteInspectionEndDate")))return null;try{LocalDate a=LocalDate.parse(s(v.get("siteInspectionStartDate"))),b=LocalDate.parse(s(v.get("siteInspectionEndDate")));return a.isAfter(b)?"The inspection start date is after the end date; review both values.":null;}catch(RuntimeException ex){return "Use valid ISO dates for the inspection period.";}}
 static void baseRules(Context c){
  Boolean two=c.b("twoEnvelopeTendering"), domestic=c.b("domesticBlocks"), permission=c.b("precastFacadePermission"), foundation=c.b("contractorDesignedFoundations"), wto=c.b("wtoGpaApplies"), railway=c.b("railwayProtectionAreaWorks");String mode=c.str("electronicTendering"), arrangement=c.str("subcontractArrangement");boolean knownMode=Arrays.asList("L10Pro","Hardcopy").contains(mode);
  c.set("NTT-1E-FACADE",action(c.b("precastFacadeTenderBasis"),"delete"),null,"Keep/delete only 1(e); the tender basis is independent of permission to propose facades.","仅按投标基础保留／删除1(e)，与允许提出外墙方案分别判断。","precastFacadeTenderBasis");
  c.set("NTT-2-L10PRO",knownMode?("L10Pro".equals(mode)?"retain":"delete"):"pending",null,"Select the complete issue-format alternative, including its continuation; keep DVD-ROM checks.","选择完整发放格式分支及续段，保留DVD-ROM检查。","electronicTendering");
  c.set("NTT-2-PAPER",knownMode?("Hardcopy".equals(mode)?"retain":"delete"):"pending",null,"Paper BQ issue retains the specified PDF, Excel and DVD companion requirements.","纸本BQ发放仍保留指定PDF、Excel和DVD配套要求。","electronicTendering");
  for(String id:Arrays.asList("NTT-3C-L10PRO","NTT-3C-PAPER"))c.set(id,!Boolean.TRUE.equals(two)||!knownMode?"pending":(id.endsWith("L10PRO")=="L10Pro".equals(mode)?"retain":"delete"),null,"Standard Envelope 2 return wording requires the adopted two-envelope procedure and issue format. Other procedures require target-specific wording.","标准第二信封回标需采用双信封及明确发放格式；其他程序须逐目标采用改文。","twoEnvelopeTendering","electronicTendering","otherTenderingArrangement");
  for(String id:Arrays.asList("NTT-3AB-PROCEDURE","NTT-4B-PROCEDURE","NTT-5D-PROCEDURE","NTT-6-PROCEDURE","NTT-7-PROCEDURE"))c.set(id,Boolean.TRUE.equals(two)?"retain":"pending",null,"Retain the standard two-envelope provision, or adopt exact replacement wording for this target. Do not invent scoring weights.","保留标准双信封条文；其他程序逐目标采用准确改文，不编造评分权重。","twoEnvelopeTendering","otherTenderingArrangement");
  c.set("NTT-9-WTO",action(wto,"not_used"),null,"WTO applicability is a business decision; No retains number 9 with Not used.","WTO适用由业务判断；否时保留9编号并写Not used。","wtoGpaApplies");
  Boolean bond=and(c.b("foundationIncluded"),c.b("periodAtLeast39Months"));c.derived.put("g1aTrigger",bond);c.derived.put("bondAppendix",bond==null?null:bond?"G1a":"G1");
  c.set("NTT-10-BOND-REFERENCE",bond==null?"pending":"amend",bond==null?null:bond?"G1a":"G1","Select G1a only when combined foundation AND at least 39 months are true; an explicit No selects G1.","基础合并合约且工期至少39个月同时为是才用G1a；任一明确否用G1。","foundationIncluded","periodAtLeast39Months","contractPeriodMonths");
  c.derived.put("nscApplicable","NSC".equals(arrangement)?Boolean.TRUE:"BSSSC".equals(arrangement)?Boolean.FALSE:null);
  c.set("NTT-13-SUBCONTRACT","NSC".equals(arrangement)?"retain":"BSSSC".equals(arrangement)&&answered(c.v.get("nscAlternativeText"))?"amend":"pending", "BSSSC".equals(arrangement)?c.v.get("nscAlternativeText"):null,"NSC retains the standard wording; BSSSC uses the exact adopted NTT13 replacement. Preserve the clause number and requirement.","NSC保留标准文字；BSSSC使用本次准确采用NTT13改文，保留条号及义务。","subcontractArrangement","nscAlternativeText");
  c.set("NTT-17-RAILWAY",action(railway,"not_used"),null,"No Works in the railway protection area means number 17 remains with Not used; plan availability is independent.","无铁路保护区工程时保留17号并写Not used；图则可查阅是独立条件。","railwayProtectionAreaWorks");
  for(String id:Arrays.asList("NTT-10-SCC-REFERENCE","NTT-13-SCC-REFERENCE","NTT-16-HOMES-REFERENCE","sct-appendix-reference-check"))c.source(id,"Verify the actual edition / appendix namespace and adopt a sourced mapping. Similar clause numbers are not evidence.","核对实际版次／附录命名空间并采用有依据映射；相似条号不是证据。");
  c.source("NTT-GUIDANCE-CLEANUP","Remove only fulfilled editing instructions after their selected targets are applied; unresolved source instructions remain for review.","仅在目标修改落实后清除已完成编辑指引；未决来源指引留待核对。");
  c.set("sct-issue-alternative",knownMode?"amend":"pending",knownMode?mode:null,"Choose SCT1 Alternative (a)/(b) in full, keeping continuation and actual Bill distribution.","完整选择SCT1(a)／(b)及续段，按实际Bills分发。","electronicTendering","billNos");
  c.set("sct-pricing-return-alternative",knownMode?"amend":"pending",knownMode?mode:null,"SCT3 follows BQ format, retaining required printed return and priced DVD / Excel companion. Reconcile a custom SCT5 separately.","SCT3跟随BQ格式，保留必要打印回标及已报价DVD／Excel副本；另核定制SCT5。","electronicTendering","twoEnvelopeTendering");
  c.set("sct-drawing-media",knownMode?"retain":"pending",null,"Retain drawings supplied as specified PDF / DXF and the correct inspection references; paper BQ is not all-paper documents.","保留指定PDF／DXF图纸及查阅引用；纸本BQ不等于所有文件纸本。","electronicTendering");
  Boolean tradesKnown="BSSSC".equals(arrangement)&&c.v.get("subcontractors") instanceof List;List<Object> trades=list(c.v.get("subcontractors"));
  c.set("sct-fire-index-reference",!tradesKnown?"pending":trades.contains("Fire services")&&trades.contains("Fire services and water pump")?"pending":"amend",trades.contains("Fire services and water pump")?"Fire services and water pump":"Fire services","Use the adopted package scope; two fire categories require proof of different scopes. Confirm old SCC20.x edition before changing reference.","按采用分包范围选择；两种消防名称需核不同范围，旧SCC20.x引用须核版次。","subcontractArrangement","subcontractors");
  if(!"pending".equals(c.a("sct-fire-index-reference").get("action")))c.source("sct-fire-index-reference","The selected fire package is known, but the supplied SCT references old SCC20.2/20.3. Adopt the verified edition mapping before replacement.","消防分包已知，但SCT引用旧SCC20.2／20.3；先采用核实版次映射。","subcontractors");
  c.set("sct-domestic-entire-clause",action(domestic,"not_used"),null,"No domestic blocks makes SCT4 Not used; do not infer from CON8 or precast facade permission.","无住宅楼时SCT4为Not used，不由CON8或外墙许可代答。","domesticBlocks");
  c.set("sct-payment-option",Boolean.FALSE.equals(domestic)?"not_adopted":and(domestic,permission)==null?"pending":"amend",permission==null?null:permission?"Option 2":"Option 1","SCT4(2) selects Option 1 without facade permission, Option 2 with permission; preserve parent applicability.","SCT4(2)无外墙许可选1，有许可选2；先保持父条適用关系。","domesticBlocks","precastFacadePermission");
  c.set("sct-tender-system",two==null?"pending":two?"retain":answered(c.v.get("otherTenderingArrangement"))?"amend":"pending",Boolean.FALSE.equals(two)?c.v.get("otherTenderingArrangement"):null,"A non-two-envelope system requires the adopted whole SCT5 replacement plus target-specific NTT/SCC reference updates.","非双信封需采用SCT5整段替换及逐目标NTT／SCC引用更新。","twoEnvelopeTendering","otherTenderingArrangement");
  for(String id:Arrays.asList("sct-foundation-assessment","sct-envelope-foundation"))c.set(id,Boolean.FALSE.equals(two)&&id.startsWith("sct-envelope")?"not_adopted":Boolean.FALSE.equals(foundation)?"delete":"pending",null,"No contractor-designed foundations deletes SCT6(1)(b) and its whole SCT5 row; a positive answer needs the verified SCC8.2 edition/adoption relation.","承包人不设计基础时删SCT6(1)(b)及SCT5整行；肯定需核SCC8.2版次及采用。","contractorDesignedFoundations","twoEnvelopeTendering");
  Boolean site=c.b("siteFormationWorks");c.set("sct-envelope-site-formation",Boolean.FALSE.equals(two)?"not_adopted":Boolean.FALSE.equals(site)?"delete":"pending",null,"No site formation deletes the entire #f row; Yes also requires sourced PRE.B9.260(4) applicability.","无场地平整删整行#f；是还需有依据的PRE.B9.260(4)适用。","siteFormationWorks","twoEnvelopeTendering");
  c.source("sct-site-formation-submissions",Boolean.FALSE.equals(site)?"Site formation is No. Adopt the agreed negative output form for SCT6(1)(c); deleting #f does not settle that output form.":"Site formation submission needs the project fact AND actual PRE.B9.260(4) use, without asking for future tenderer directors.",Boolean.FALSE.equals(site)?"场地平整为否；须采用SCT6(1)(c)负向形式，删除#f不裁定子项形式。":"场地平整提交需工程事实及实际PRE.B9.260(4)采用，不询问未来投标人董事。","siteFormationWorks");
  c.set("sct-envelope-domestic",Boolean.FALSE.equals(two)?"not_adopted":domestic==null?"pending":domestic?"retain":"delete",null,"Keep/delete the whole domestic proposal row, including its letter; final lettering is derived from retained rows.","按住宅范围保留／删除整个提案行及字母；最终字母由保留行派生。","twoEnvelopeTendering","domesticBlocks");
  c.set("sct-envelope-special-payment",Boolean.FALSE.equals(two)?"not_adopted":permission==null||domestic==null?"pending":!permission?"delete":domestic?"retain":"pending",null,"Payment row follows facade permission; domestic No with permission Yes requires adopted mixed-reference wording.","付款行跟随外墙许可；住宅否但许可是需采用组合引用改文。","twoEnvelopeTendering","precastFacadePermission","domesticBlocks");
  c.set("sct-envelope-price-documents",Boolean.FALSE.equals(two)?"not_adopted":Boolean.TRUE.equals(two)&&knownMode?"amend":"pending",knownMode?mode:null,"Keep the adopted Envelope 2 price-document format; all priced electronic companions remain as required.","采用第二信封计价文件格式，并保留规定的已报价电子副本。","twoEnvelopeTendering","electronicTendering","billNos");
  c.set("sct-photocopy-rates",Boolean.FALSE.equals(two)?"not_adopted":Boolean.TRUE.equals(two)&&number(c.v.get("photocopyRateUpToA3"))!=null&&number(c.v.get("photocopyRateAboveA3"))!=null?"amend":"pending",map("upToA3",c.v.get("photocopyRateUpToA3"),"aboveA3",c.v.get("photocopyRateAboveA3")),"Replace only both stated photocopy rates; zero is valid, negative/non-finite values require review.","仅替换两项抄印费率；零有效，负数／非有限值需复核。","twoEnvelopeTendering","photocopyRateUpToA3","photocopyRateAboveA3");
  c.set("sct-original-hardcopy-wording",Boolean.FALSE.equals(two)?"not_adopted":Boolean.TRUE.equals(two)&&knownMode?"amend":"pending",mode,"L10Pro deletes only the starred BQ/General Summary phrase, retaining the Form of Tender; paper retains it.","L10Pro仅删标记BQ／总汇短语并保留Form of Tender；纸本保留该内容。","twoEnvelopeTendering","electronicTendering");
  c.set("sct-domestic-proposals",action(domestic,"not_used"),null,"No domestic blocks marks the whole SCT6(2) Not used while retaining its number.","无住宅楼时SCT6(2)整款Not used并保留编号。","domesticBlocks");
  c.set("sct-domestic-payment-proposal",Boolean.FALSE.equals(domestic)?"not_adopted":Boolean.TRUE.equals(domestic)&&Boolean.TRUE.equals(permission)?"retain":"pending",null,"Domestic Yes / permission No has a source-rule output-form ambiguity; adopt an exact target action instead of inventing a gate.","住宅是／外墙许可否的输出形式需源文规则裁定；可本次采用目标动作，不造门禁。","domesticBlocks","precastFacadePermission");
  c.set("sct-domestic-submission-liability",Boolean.FALSE.equals(domestic)?"not_used":and(domestic,permission)==null?"pending":permission?"retain":"amend",Boolean.FALSE.equals(permission)?"delete specified payment phrase":null,"Without domestic blocks the entire (c) is Not used; without facade permission delete only its specified payment wording.","无住宅时(c)整项Not used；无外墙许可时仅删指定付款短语。","domesticBlocks","precastFacadePermission");
  List<Map<String,Object>> requirements=requirements(c.v);c.derived.put("submissionRequirements",requirements);
  Object general=c.v.get("additionalSubmissions");c.set("sct-additional-submissions",general instanceof List?requirements.isEmpty()?"not_adopted":"amend":"pending",requirements,"A shared adopted requirement is inserted once, preserving all sources and its applicable trigger; absence is not an explicit empty list.","共享采用要求只插入一次，保留所有来源及触发范围；未知不等于空清单。","additionalSubmissions","pseSubmissions","domesticBlocks","volumetricPrecastComponents");
  Boolean con8=and(domestic,c.b("volumetricPrecastComponents"));c.set("sct-volumetric-pse-submissions",Boolean.FALSE.equals(con8)?"not_adopted":Boolean.TRUE.equals(con8)&&c.v.get("pseSubmissions")instanceof List?"retain":"pending",null,"CON8/PSE requirements use the same requirement collection; this action does not insert them a second time.","CON8／PSE要求使用同一集合；此动作不再次插入。","domesticBlocks","volumetricPrecastComponents","pseSubmissions");
  c.set("sct-structural-submission-signature",action(c.b("rseSubmissionsRequired"),"not_used"),null,"Use the specific RSE submission fact. No marks only SCT6(3)(d) Not used; extra/PSE empty cannot answer it.","按专项RSE提交事实处理；否仅将SCT6(3)(d)写Not used，一般／PSE空清单不能代答。","rseSubmissionsRequired");
  boolean contact=c.has("projectArchitectPost","projectArchitectSalutation","projectArchitectName","projectArchitectPhone")&&(!"Other".equals(c.str("projectArchitectSalutation"))||c.has("projectArchitectOtherTitle"));
  c.set("sct-architect-contact",contact?"amend":"pending",map("post",c.v.get("projectArchitectPost"),"title","Other".equals(c.str("projectArchitectSalutation"))?c.v.get("projectArchitectOtherTitle"):c.v.get("projectArchitectSalutation"),"name",c.v.get("projectArchitectName"),"phone",c.v.get("projectArchitectPhone")),"Insert the adopted contact fields; actual Other title is verbatim user text, never an enum label.","填写采用联系人字段；Other实际称谓是用户原文，不是选项标签。","projectArchitectPost","projectArchitectSalutation","projectArchitectOtherTitle","projectArchitectName","projectArchitectPhone");
  c.set("sct-specification-inspection-address",c.has("specificationInspectionFloor","specificationInspectionBlock")?"amend":"pending",map("floor",c.v.get("specificationInspectionFloor"),"block",c.v.get("specificationInspectionBlock")),"Use the Specification Library inspection address, independent of drawings.","采用规范资料库查阅地址，与图纸地点分别保存。","specificationInspectionFloor","specificationInspectionBlock");
  c.set("sct-drawings-inspection-address",c.has("drawingsInspectionFloor","drawingsInspectionBlock")?"amend":"pending",map("floor",c.v.get("drawingsInspectionFloor"),"block",c.v.get("drawingsInspectionBlock")),"Use the drawings inspection address, independent of the Specification Library.","采用图纸查阅地点，与规范资料库分别保存。","drawingsInspectionFloor","drawingsInspectionBlock");
  c.set("sct-site-inspection",c.has("siteInspectionStartDate","siteInspectionEndDate","siteVisitRestrictions")?"amend":"pending",map("start",c.v.get("siteInspectionStartDate"),"end",c.v.get("siteInspectionEndDate"),"restrictions",c.v.get("siteVisitRestrictions")),"Insert the adopted valid date interval and actual restrictions; retain the at-least-seven-days application rule.","填写有效采用日期区间及实际限制，保留提前至少七天申请的规定。","siteInspectionStartDate","siteInspectionEndDate","siteVisitRestrictions");
  c.set("sct-precast-payment-clause",action(permission,"not_used"),null,"SCT10 follows required OR permitted facade proposal under APE2.A410. It has no invented domestic prerequisite.","SCT10跟随APE2.A410要求或允许外墙方案；不添加住宅前提。","precastFacadePermission");
  c.set("sct-wto-applicability",action(wto,"not_used"),null,"Reuse the NTT WTO applicability value in SCT14.","SCT14复用NTT的WTO适用值。","wtoGpaApplies");
  c.set("sct-custom-system-cross-references",Boolean.TRUE.equals(two)?"retain":"pending",null,"Verify each adopted custom procedure target at SCT7/16/17; one free description does not complete the reference map.","逐位置核SCT7／16／17定制程序引用；一段自由说明不等于全部映射完成。","twoEnvelopeTendering","otherTenderingArrangement");
  c.set("sct-contract-identity-instructions",Boolean.FALSE.equals(two)?"not_adopted":action(two,"not_adopted"),null,"Preserve tenderer packaging instructions; project identity is not a replacement for literal Contract Title instruction wording.","保留投标人包装指令，项目身份不能替换指令中的Contract Title字样。","twoEnvelopeTendering","contractTitle");
  billRules(c);bsRules(c,tradesKnown,trades);treeRules(c);
  c.set("scc-advance-adoption",action(c.b("advancePaymentAdopted"),"not_adopted"),null,"Advance adoption is the business user's current decision; no internal policy date/12-month approval gate.","预付款采用由业务用户本次决定，不加内部日期／12个月审批门禁。","advancePaymentAdopted");
  Boolean advance=c.b("advancePaymentAdopted");c.set("scc-advance-repayment-standard",Boolean.FALSE.equals(advance)?"not_adopted":advance==null?"pending":"amend",map("months",c.v.getOrDefault("advanceRepaymentMonths",6),"firstCertificate",c.v.getOrDefault("advanceRepaymentFirstCertificate",7)),"Use six/seventh standard values unless an actual project-specific repayment amendment is adopted; never infer from foundation presence.","无项目特定采用改文时保留六个月／第七期；不从基础工程推定修改。","advancePaymentAdopted","advanceRepaymentMonths","advanceRepaymentFirstCertificate");
  c.set("scc-railway-adoption",action(railway,"not_adopted"),null,"Railway applicability is any Works inside the protection area; plans and EOT are nested independent decisions.","铁路适用为任何工程在保护区内；图则和延期为独立子判断。","railwayProtectionAreaWorks");
  c.set("scc-railway-plan-inspection",Boolean.FALSE.equals(railway)?"not_adopted":and(railway,c.b("railwayProtectionPlansAvailable"))==null?"pending":Boolean.TRUE.equals(c.b("railwayProtectionPlansAvailable"))?"retain":"delete",null,"If plans unavailable, delete only the final public-inspection sentence and retain the definition; flag project-provided plans.","图则不可查时仅删除末尾公开查阅句，保留定义并提示项目另备图。","railwayProtectionAreaWorks","railwayProtectionPlansAvailable");
  c.set("scc-foundation-version-reference",Boolean.FALSE.equals(foundation)?"not_adopted":"pending",null,"SCT's SCC8.2 reference needs actual edition mapping; SCC8.304 has independent design AND execution conditions.","SCT旧SCC8.2须实际版次映射；8.304有独立设计及施工条件。","contractorDesignedFoundations");
 }
 static void billRules(Context c){Object raw=c.v.get("billNos");List<Object> bills=list(raw);boolean complete=raw instanceof List&&invalid("billNos",raw)==null;boolean roles=complete;
  for(String[] pair:new String[][]{{"1","Preliminaries"},{"2","Preambles"}}){boolean match=false;for(Object o:bills){Map<String,Object>b=asMap(o);if(pair[0].equals(s(b.get("number")))&&pair[1].equalsIgnoreCase(s(b.get("description")).trim())&&(!answered(b.get("purpose"))||pair[1].toLowerCase(Locale.ROOT).equals(s(b.get("purpose")))))match=true;}roles&=match;}
  c.set("sct-shared-bill-list",complete?"amend":"pending",complete?bills:null,"Reuse exact adopted numbers/descriptions; role/type/placement are independent sourced attributes.","复用准确采用编号及说明；用途／类型／分发为独立有据属性。","billNos");
  c.set("sct-bill-body-summary",roles&&c.has("electronicTendering")?"amend":"pending",roles?bills:null,"Standard Bill1/2 body and collection/summary placement is valid only for the corresponding adopted roles; Not Preliminaries is not Preliminaries.","标准Bill1／2正文及汇总分发只适用于对应采用用途；Not Preliminaries不是Preliminaries。","billNos","electronicTendering");
  boolean placement=complete&&!bills.isEmpty();for(Object o:bills){Map<String,Object>b=asMap(o);placement&=Arrays.asList("BQ","SOR").contains(s(b.get("type")))&&answered(b.get("purpose"))&&answered(b.get("placement"))&&(!"custom".equals(b.get("placement"))||answered(b.get("placementText")));}
  c.set("sct-project-bq-sor-placement",placement?"amend":"pending",placement?bills:null,"Use adopted per-row pricing type and distribution, including specific addenda overrides. SOR is not automatically all hardcopy.","按每行采用计价类型及分发处理，包括补遗覆盖；SOR不自动全纸本。","billNos","electronicTendering");
  List<String> ordinary=new ArrayList<>();boolean typesKnown=complete;for(Object o:bills){Map<String,Object>b=asMap(o);typesKnown&=Arrays.asList("BQ","SOR").contains(s(b.get("type")))&&answered(b.get("purpose"));if("BQ".equals(b.get("type"))&&"general".equals(b.get("purpose")))ordinary.add(s(b.get("number")));}
  c.derived.put("ordinaryBqNumbers",ordinary);c.set("sct-envelope-bill-range",Boolean.FALSE.equals(c.b("twoEnvelopeTendering"))?"not_adopted":Boolean.TRUE.equals(c.b("twoEnvelopeTendering"))&&typesKnown?"amend":"pending",typesKnown?ordinary:null,"Use explicit adopted ordinary BQ numbers; compress only actual consecutive numeric sequences, never 3 through the highest mixed Bill/SOR number.","采用普通BQ实际编号；仅压缩真实连续数字，不用混合Bill／SOR最高编号猜3至末号。","billNos","twoEnvelopeTendering");
 }
 static void bsRules(Context c,boolean known,List<Object> trades){String arr=c.str("subcontractArrangement");boolean nsc="NSC".equals(arr);String names=join(trades);for(String id:Arrays.asList("scc-bs-definition","scc-bs-types-effective-value","scc-bs-types-bs-sums"))c.set(id,known?"amend":"pending",known?names:null,nsc?"The supplied SCC is BSSSC. Use the correct NSC template or a sourced target amendment; do not globally rename it.":"Reuse the exact selected specialist trade categories at every target; names are not company names.",nsc?"所给SCC为BSSSC；采用正确NSC模板或有依据目标改文，不能全局换名。":"所有目标复用选中专业工种名称，不是公司名。","subcontractArrangement","subcontractors");
  String[] clauses={"SCC20.302","SCC20.303","SCC20.304"},types={"Electrical","Fire services","Fire services and water pump"},purposes={"electricalSafety","fireSafety","fireWaterSafety"};List<String> refs=new ArrayList<>();
  for(int i=0;i<clauses.length;i++){Boolean adopted=known?trades.contains(types[i]):null;if(Boolean.TRUE.equals(adopted))refs.add(clauses[i]);c.set("scc-specialist-"+clauses[i],action(adopted,"not_adopted"),null,"Adopt only the fluctuation clause for the included specialist Works; standard index months remain unless an actual target amendment is adopted.","仅采用所含专业工程波动条款；标准指数月份除真实目标采用改文外保留。","subcontractArrangement","subcontractors");safety(c,"scc-safety-pricing-"+clauses[i],purposes[i],adopted);}
  c.derived.put("specialistFluctuationReferences",known?refs:null);safety(c,"scc-safety-pricing-general","bsSafety",known?!trades.isEmpty():null);
 }
 static void safety(Context c,String id,String purpose,Boolean adopted){List<Map<String,Object>> matches=new ArrayList<>();boolean complete=c.v.get("billNos")instanceof List;for(Object o:list(c.v.get("billNos"))){Map<String,Object>b=asMap(o);if(purpose.equals(b.get("purpose"))){matches.add(b);complete&=Arrays.asList("BQ","SOR").contains(s(b.get("type")))&&answered(b.get("number"));}}
  String result=Boolean.FALSE.equals(adopted)?"not_adopted":Boolean.TRUE.equals(adopted)&&complete&&!matches.isEmpty()?"amend":"pending";c.set(id,result,"amend".equals(result)?matches:null,"Reference only the adopted safety-purpose Bill / Schedule of the correct pricing type and scope. Do not copy all Bills or infer SOR from trade names.","仅引用相应用途、计价类型及范围的采用安全Bill／Schedule；不复制全部Bills，不由工种猜SOR。","billNos","subcontractors","subcontractArrangement");}
 static void treeRules(Context c){Object raw=c.v.get("oldValuableTrees");List<Object> trees=list(raw);boolean valid=raw instanceof List&&invalid("oldValuableTrees",raw)==null;int count=valid?trees.size():-1;c.derived.put("oldValuableTreeCount",valid?count:null);
  for(String id:Arrays.asList("scc-ovt-definitions","scc-ovt-aftercare"))c.set(id,!valid?"pending":count==0?"not_adopted":"retain",null,"Reuse the valid tree identities; explicit empty means none, and incomplete/duplicate rows never create extra trees.","复用有效树木身份；明确空清单为无，缺号／重复行不能造额外树。","oldValuableTrees");
  c.set("scc-ovt-protection",!valid?"pending":count==0?"not_adopted":count==1?"retain":c.has("ovtProjectSpecificText")?"amend":"pending",valid&&count>1?c.v.get("ovtProjectSpecificText"):null,"One tree uses the standard clause; multiple trees require actual adopted project wording covering all trees, not comma-joined serials.","单株采用标准条文；多株须准确采用覆盖全部树木的项目改文，不能逗号拼号。","oldValuableTrees","ovtProjectSpecificText");
  String serial=count==1?(trees.get(0) instanceof String?s(trees.get(0)):s(asMap(trees.get(0)).get("serial"))):null;
  for(String id:Arrays.asList("scc-ovt-number-protection","scc-ovt-number-liability","scc-ovt-number-proviso"))c.set(id,!valid?"pending":count==1?"amend":"not_adopted",serial,"Fill the same single-tree serial at all three actual Tree No. positions; zero/multiple-tree clauses do not use singular blanks.","三处Tree No.填写同一单株编号；零株／多株不采用标准单株空白。","oldValuableTrees");
  c.set("scc-ovt-external-crosschecks",valid&&count==0?"not_adopted":"pending",null,"Verify tree-specific liability sums, two distinct periods in Form of Tender and arborist/aftercare in Specification; adopt sourced target mapping after verification.","核Form of Tender逐树金额及两个不同期间、规范arborist／后护；核实后采用有据目标映射。","oldValuableTrees");c.a("scc-ovt-external-crosschecks").put("pendingKind","SourceCheck");
 }
 static void additionalRules(Context c){
  c.add("NTT-5F-EXCISION","NTT","5(f)","P243–244",action(c.b("worksSubjectToExcision"),"delete"),null,"Use one excision fact across NTT and SCC; No deletes only NTT5(f).","NTT和SCC复用同一可剔除工程事实；否仅删NTT5(f)。","worksSubjectToExcision");
  c.add("scc-excision","SCC","9.301","P953–955",action(c.b("worksSubjectToExcision"),"not_adopted"),null,"Reuse NTT excision applicability; this is not a Bill-name keyword inference.","复用NTT可剔除工程适用事实，不从Bill名称关键词推断。","worksSubjectToExcision");
  for(String[] target:new String[][]{{"scc-permit-definition","1.306","P180–196"},{"scc-permit-works","22.303","P1823–1880"}})c.add(target[0],"SCC",target[1],target[2],action(c.b("excavationPermitRequired"),"not_adopted"),null,"Reuse the actual Excavation Permit requirement; ordinary excavation or foundation presence is insufficient.","复用实际开挖许可要求；普通挖掘或有基础不能代答。","excavationPermitRequired");
  c.add("scc-ssf","SCC","8.306","P910–927",action(c.b("subsidisedSaleFlatsProduction"),"not_adopted"),null,"SSF production is distinct from domestic blocks.","SSF生产与一般住宅楼分别判断。","subsidisedSaleFlatsProduction");
  String flats=c.str("showFlatsRequirement");c.add("scc-show-flats","SCC","22.306","P1941–1957",!answered(flats)?"pending":"none".equals(flats)?"not_adopted":"retain",null,"Exhibition/show flat requirement is independent of residential presence; no new quantity/date blanks are invented.","展览／示范单位要求独立于住宅范围，不造额外数量／日期空白。","showFlatsRequirement");
  designRules(c);measurementRules(c);warrantyRules(c);sectionRules(c);legalRules(c);
 }
 static void designRules(Context c){Object raw=c.v.get("designResponsibilities");List<Object> rows=list(raw);boolean known=raw instanceof List;List<String> both=new ArrayList<>();boolean uncertain=false;boolean any=false;for(Object o:rows){Map<String,Object> r=asMap(o);String component=s(r.get("component"));Boolean responsibility=and(truth(r.get("design")),truth(r.get("execution")));if(responsibility==null)uncertain=true;else if(responsibility){any=true;both.add(component);}}
  Boolean allAny=known?(any?Boolean.TRUE:uncertain?null:false):null;Boolean foundationAny=null,structuralAny=null;
  if(known){boolean fa=false,sa=false,fu=uncertain,su=uncertain;for(String component:both){if(Arrays.asList("piling","pilecaps","footings").contains(component))fa=true;if(Arrays.asList("piling","pilecaps").contains(component))sa=true;if("footings".equals(component)){Boolean scope=c.b("footingsServeBuildingsOrMajorExternalStructures");if(Boolean.TRUE.equals(scope))sa=true;else if(scope==null)su=true;}}foundationAny=fa?Boolean.TRUE:fu?null:Boolean.FALSE;structuralAny=sa?Boolean.TRUE:su?null:Boolean.FALSE;}
  c.derived.put("contractorDesignAndExecutionComponents",both);c.derived.put("scc8304Adopted",foundationAny);
  Boolean timing=c.b("designEstablishedAtTenderAcceptance");Boolean submitted=c.b("foundationDesignSubmittedWithTender");Boolean adjustment=and(allAny,timing);if(Boolean.TRUE.equals(foundationAny)&&Boolean.TRUE.equals(submitted))adjustment=true;
  for(String[] t:new String[][]{{"scc-design-adjustment","5.308","P469–474"},{"scc-design-foundation-warranty","7.302","P546–550"},{"scc-design-adverse-ground","8.304","P882–888"},{"scc-design-failure-cost","22.305","P1925–1937"}}){Boolean applicable="5.308".equals(t[1])?adjustment:"8.304".equals(t[1])?foundationAny:structuralAny;List<String> targetComponents=new ArrayList<>();for(String component:both)if("5.308".equals(t[1])||Arrays.asList("piling","pilecaps","footings").contains(component)&&("8.304".equals(t[1])||!"footings".equals(component)||Boolean.TRUE.equals(c.b("footingsServeBuildingsOrMajorExternalStructures"))))targetComponents.add(component);c.add(t[0],"SCC",t[1],t[2],applicable==null?"pending":applicable?"amend":"not_adopted",Boolean.TRUE.equals(applicable)?targetComponents:null,"Apply this clause's exact design AND execution, component-scope and tender-timing conditions; do not substitute the SCT design-only fact.","按本条设计及施工、构件范围、投标时点条件处理；不以SCT仅设计事实替代。","designResponsibilities","footingsServeBuildingsOrMajorExternalStructures","designEstablishedAtTenderAcceptance","foundationDesignSubmittedWithTender");}
  Boolean designInput=known?Boolean.FALSE:null;for(Object o:rows){Boolean d=truth(asMap(o).get("design"));if(Boolean.TRUE.equals(d)){designInput=true;break;}if(d==null)designInput=null;}
  Boolean quote=and(designInput,c.b("quotationBeforeVariation"));c.add("scc-variation-quotation","SCC","11.305","P1087–1123",action(quote,"not_adopted"),null,"Adopt only the business-selected quotation arrangement for actual Contractor design input; execution responsibility is not a prerequisite.","对真实承包人设计输入采用业务选定报价安排；不要求承包人承担施工。","designResponsibilities","quotationBeforeVariation");
 }
 static void measurementRules(Context c){String scheme=c.str("pricingScheme");Boolean provisional=c.b("allBqQuantitiesProvisional");Boolean mixed="BQ_SOR".equals(scheme)?Boolean.TRUE:Arrays.asList("BQ","SOR").contains(scheme)?Boolean.FALSE:null;Boolean full="BQ".equals(scheme)?provisional:mixed==null?null:Boolean.FALSE;
  c.derived.put("scc11301Adopted",full);c.derived.put("scc11302Adopted",mixed);c.derived.put("scc11302Option",Boolean.TRUE.equals(mixed)&&provisional!=null?provisional?"B":"A":null);
  c.add("scc-all-provisional-definition","SCC","1.304","P156–164",action(full,"not_adopted"),null,"SCC1.304 follows actual 11.301 adoption, not provisional quantities in a mixed BQ/SOR scheme.","SCC1.304跟随实际11.301采用，不从混合BQ／SOR全暂定推定。","pricingScheme","allBqQuantitiesProvisional");
  c.add("scc-bq-measurement","SCC","11.301","P979–1001",action(full,"not_adopted"),null,"Pure BQ with all quantities provisional adopts 11.301 and 1.304; do not simultaneously adopt 11.302.","纯BQ全暂定采用11.301及1.304，不同时采用11.302。","pricingScheme","allBqQuantitiesProvisional");
  c.add("scc-mixed-measurement","SCC","11.302","P1007–1067",Boolean.FALSE.equals(mixed)?"not_adopted":Boolean.TRUE.equals(mixed)&&provisional!=null?"amend":"pending",Boolean.TRUE.equals(mixed)&&provisional!=null?provisional?"Option B":"Option A":null,"Mixed BQ/SOR adopts only 11.302: all provisional selects B, otherwise A; delete the other option.","混合BQ／SOR仅采用11.302：全暂定选B，否则A，并删除另一个分支。","pricingScheme","allBqQuantitiesProvisional");
 }
 static void warrantyRules(Context c){Boolean domestic=c.b("domesticBlocks"),tsw=c.b("projectInTinShuiWai");c.add("scc-structural-warranty","SCC","7.303","P554–592",Boolean.FALSE.equals(domestic)?"not_adopted":Boolean.TRUE.equals(domestic)&&tsw!=null?"amend":"pending",Boolean.TRUE.equals(domestic)&&tsw!=null?tsw?"twenty":"ten":null,"Reuse domestic construction scope; Tin Shui Wai selects twenty years, other projects ten.","复用住宅建造范围；天水围二十年，其他十年。","domesticBlocks","projectInTinShuiWai");
  Boolean roof=and(c.b("roofingInstallationIncluded"),c.b("roofingWarrantyRequired")),refuge=and(c.b("refugeFloorInstallationIncluded"),c.b("refugeFloorWarrantyRequired")),other=c.b("otherWaterproofingWarrantyRequired");if(Boolean.TRUE.equals(other)&&!c.has("otherWaterproofingSpecificationAreas"))other=null;List<String> selected=new ArrayList<>();if(Boolean.TRUE.equals(roof))selected.add("Roofing Installation");if(Boolean.TRUE.equals(refuge))selected.add("Refuge Floor Installation");if(Boolean.TRUE.equals(other))selected.add("Waterproofing System Installation");
  c.add("scc-waterproof-warranty","SCC","7.304","P598–646",roof==null||refuge==null||other==null?"pending":selected.isEmpty()?"not_adopted":"amend",selected,"Apply the chosen warranty installations consistently at all listed positions; Other requires actual Specification-designated areas.","所有列出位置同步采用质保范围；Other须规范实际指定区域。","roofingInstallationIncluded","roofingWarrantyRequired","refugeFloorInstallationIncluded","refugeFloorWarrantyRequired","otherWaterproofingWarrantyRequired","otherWaterproofingSpecificationAreas");
  for(String[]t:new String[][]{{"scc-acrylic-warranty","7.305","P650–660","acrylicPaintWarrantyRequired"},{"scc-tiling-warranty","7.306","P664–690","wallTilingWarrantyRequired"},{"scc-pipe-warranty","7.308","P765–807","epoxyCastIronPipeWarrantyRequired"}})c.add(t[0],"SCC",t[1],t[2],action(c.b(t[3]),"not_adopted"),null,"Adopt the actual specified warranty requirement, not merely the presumed presence of this material.","按实际指定质保要求采用，不只凭材料通常存在推断。",t[3]);
  Boolean play=c.b("playEquipmentIncluded"),iasm=c.b("iasmIncluded");String state=play==null||iasm==null?"pending":play&&iasm?"retain":!play&&!iasm?"not_adopted":"pending";c.add("scc-play-iasm-warranty","SCC","7.307","P694–763",state,null,"Source guidance says play equipment AND IASM. A single installation requires an adopted business target decision; do not silently change AND to OR.","原文为游乐设施及IASM；仅一项存在需业务目标裁定，不静默将AND变OR。","playEquipmentIncluded","iasmIncluded");
 }
 static void sectionRules(Context c){Object raw=c.v.get("sections");List<Object>sections=list(raw);boolean known=raw instanceof List;List<String> demolition=new ArrayList<>(),other=new ArrayList<>();boolean building=false,distinct=true;for(Object o:sections){Map<String,Object>r=asMap(o);List<Object>types=list(r.get("workTypes"));if(types.contains("building")){building=true;if(types.size()>1)distinct=false;}else if(!types.isEmpty())other.add(s(r.get("designation")));if(types.size()==1&&types.contains("demolition"))demolition.add(s(r.get("designation")));}
  String choice=c.str("weatherEotClause");String d=c.str("demolitionOnlySection");if(d.isEmpty()&&demolition.size()==1)d=demolition.get(0);boolean validD=demolition.contains(d);
  Boolean eligible=known?and(building&&!demolition.isEmpty()&&distinct,c.b("buildingDemolitionSitesSeparated")):null;
  c.derived.put("demolitionOnlySection",validD?d:null);c.derived.put("otherWorksSections",other);
  c.add("scc-weather-8302","SCC","8.302","P827–829",!answered(choice)?"pending":"SCC8.302".equals(choice)?"retain":"not_adopted",null,"8.302 and 8.303 are mutually exclusive; neither is selected by a missing answer.","8.302与8.303互斥，缺答不默认选任一。","weatherEotClause");
  c.add("scc-weather-8303","SCC","8.303","P835–873",!answered(choice)?"pending":!"SCC8.303".equals(choice)?"not_adopted":Boolean.TRUE.equals(eligible)&&validD?"amend":"pending",validD?d:null,"8.303 requires building/demolition each in its own Section AND separated sites; reuse the only-demolition Section at all six positions.","8.303需建筑／拆卸各自Section且地盘分离；六处复用仅拆卸Section。","weatherEotClause","sections","buildingDemolitionSitesSeparated","demolitionOnlySection");
  c.add("scc-section-enhancement","SCC","11.304","P1076–1082",!known?"pending":building&&distinct&&!other.isEmpty()?"amend":"not_adopted",other,"Reuse non-building Section designations. This clause does not require 8.303's detached locations.","复用非建筑Section编号；本条不要求8.303的地盘分离。","sections");
  c.add("scc-late-possession","SCC","8.301","P815–823",action(c.b("latePossessionAdopted"),"not_used"),null,"Special late-possession adoption belongs to the business user. SQS/CA consultation remains a notice, not an approval gate.","特殊迟交地盘由业务用户采用；SQS／CA咨询仅提示，不设审批门禁。","latePossessionAdopted");
  Boolean loss=c.b("additionalLossAdopted");boolean lossSections=sectionNamesValid(c.str("additionalLossSpecifiedSections"),sections)&&sectionNamesValid(c.str("additionalLossRelevantSection"),sections);c.add("scc-additional-loss","SCC","8.305","P894–906",Boolean.FALSE.equals(loss)?"not_adopted":Boolean.TRUE.equals(loss)&&lossSections?"amend":"pending",map("specified",c.v.get("additionalLossSpecifiedSections"),"relevant",c.v.get("additionalLossRelevantSection")),"Keep the explicit exceptional-loss adoption and reuse actual Sections; consultation is a notice.","保留明确特殊损失采用，复用实际Section；咨询仅提示。","additionalLossAdopted","sections","additionalLossSpecifiedSections","additionalLossRelevantSection");
  Boolean training=and(c.b("policeTrainingAdopted"),c.b("demolitionStandaloneBuilding"),c.b("siteSuitableForTrainingFirstMonth"));c.add("scc-demolition-training","SCC","8.308","P929–951",action(training,"not_adopted"),null,"Training needs actual qualifying demolition and suitable site plus the adopted option; PRE.B6.612 must be coordinated.","训练需符合拆卸范围、适宜地盘及采用选项；协调PRE.B6.612。","policeTrainingAdopted","demolitionStandaloneBuilding","siteSuitableForTrainingFirstMonth","latePossessionAdopted");
 }
 static boolean sectionNamesValid(String names,List<Object>sections){if(!answered(names))return false;Set<String> ids=new HashSet<>();for(Object o:sections)ids.add(s(asMap(o).get("designation")));for(String name:names.split("[,;]"))if(!ids.contains(name.trim()))return false;return true;}
 static void legalRules(Context c){String form=c.str("contractorLegalForm");Boolean partnership=!answered(form)?c.b("partnershipClauseAdopted"):Boolean.valueOf(Arrays.asList("partnership","unincorporatedJV").contains(form));Boolean jv=!answered(form)?c.b("jointVentureClauseAdopted"):Boolean.valueOf(Arrays.asList("unincorporatedJV","incorporatedJV").contains(form));
  c.add("scc-partnership","SCC","22.308","P2030–2040",action(partnership,"not_adopted"),null,"Partnership OR unincorporated JV; unknown tender-stage form uses the business user's explicit clause adoption.","合伙或非公司联营适用；投标阶段主体未知时用用户明确条款采用。","contractorLegalForm","partnershipClauseAdopted");
  c.add("scc-joint-venture","SCC","22.309","P2044–2074",action(jv,"not_adopted"),null,"Unincorporated OR incorporated JV. This differs from the partnership clause's condition.","非公司或公司联营适用，与合伙条款条件不同。","contractorLegalForm","jointVentureClauseAdopted");
 }
 static void references(Context c){
  List<String> refs=new ArrayList<>();boolean known="BSSSC".equals(c.str("subcontractArrangement"))&&c.v.get("subcontractors")instanceof List;for(String clause:Arrays.asList("SCC20.302","SCC20.303","SCC20.304")){String a=s(c.a("scc-specialist-"+clause).get("action"));if("pending".equals(a))known=false;else if(!Arrays.asList("delete","not_used","not_adopted").contains(a))refs.add(clause);}
  c.derived.put("specialistFluctuationReferences",known?refs:null);c.set("scc-general-fluctuation-references",known?"amend":"pending",known?refs:null,"Reference the actually adopted specialist fluctuation clauses, including manual target decisions; preserve other general provisions.","引用实际采用专业波动条款，包括人工目标决定；保留其他一般条文。","subcontractArrangement","subcontractors","targetOverrides");Boolean advance=c.b("advancePaymentAdopted");c.set("scc-advance-fluctuation-references",Boolean.FALSE.equals(advance)?"not_adopted":Boolean.TRUE.equals(advance)&&known?"amend":"pending",Boolean.TRUE.equals(advance)&&known?refs:null,"Advance reference collection uses the same actual specialist clause adoption result.","预付款引用集合复用实际专业条款采用结果。","advancePaymentAdopted","subcontractArrangement","subcontractors","targetOverrides");
  String ground=s(c.a("scc-design-adverse-ground").get("action"));Boolean groundAdopted="pending".equals(ground)?null:!Arrays.asList("delete","not_used","not_adopted").contains(ground);c.derived.put("scc8304Adopted",groundAdopted);Boolean rail=c.b("railwayProtectionAreaWorks");c.set("scc-railway-eot-option",Boolean.FALSE.equals(rail)?"not_adopted":Boolean.TRUE.equals(rail)&&groundAdopted!=null?"amend":"pending",Boolean.TRUE.equals(rail)&&groundAdopted!=null?groundAdopted?"Option B":"Option A":null,"Actual SCC8.304 adoption selects railway Option B (xiv→xv, railway xiv); non-adoption selects A (xiii→xiv, railway xiii).",
  "实际采用8.304选铁路B（xiv至xv，新增xiv）；未采用选A（xiii至xiv，新增xiii）。","railwayProtectionAreaWorks","designResponsibilities","targetOverrides");
  Boolean two=c.b("twoEnvelopeTendering");Map<String,Object> procedure=c.a("sct-tender-system");boolean customStructure=Boolean.TRUE.equals(procedure.get("manual"))&&!"retain".equals(procedure.get("action"));boolean standardStructure=Boolean.TRUE.equals(two)&&!customStructure;Map<String,String>letters=new LinkedHashMap<>();boolean rowsKnown=standardStructure;int letter=0;for(String row:Arrays.asList("a","b","c","d"))letters.put(row,String.valueOf((char)('a'+letter++)));
  for(String[]row:new String[][]{{"e","sct-envelope-foundation"},{"f","sct-envelope-site-formation"},{"g","sct-envelope-domestic"},{"h","sct-envelope-special-payment"}}){String a=s(c.a(row[1]).get("action"));if("pending".equals(a))rowsKnown=false;else if(!Arrays.asList("delete","not_used","not_adopted").contains(a))letters.put(row[0],String.valueOf((char)('a'+letter++)));}
  c.derived.put("sct5SubmissionLetters",rowsKnown?letters:null);Boolean facade=c.b("precastFacadePermission");c.set("sct-special-payment-submission-reference",Boolean.FALSE.equals(facade)?"not_adopted":Boolean.TRUE.equals(facade)&&rowsKnown&&letters.containsKey("h")?"amend":"pending",rowsKnown&&letters.containsKey("h")?"SCT5(3)("+letters.get("h")+")":null,"Derive the SCT10 reference from final retained SCT5 rows. If SCT10 is Not used, no orphan internal reference remains.","SCT10引用由最终保留SCT5行派生；SCT10为Not used不留孤立内部引用。","twoEnvelopeTendering","contractorDesignedFoundations","siteFormationWorks","domesticBlocks","precastFacadePermission","targetOverrides");
  List<String>definitions=new ArrayList<>(Arrays.asList("SCC1.301","SCC1.302","SCC1.303","SCC1.307"));boolean definitionKnown=true;for(String[] d:new String[][]{{"SCC1.304","scc-all-provisional-definition"},{"SCC1.305","scc-ovt-definitions"},{"SCC1.306","scc-permit-definition"}}){String a=s(c.a(d[1]).get("action"));if("pending".equals(a))definitionKnown=false;else if(!Arrays.asList("delete","not_used","not_adopted").contains(a))definitions.add(d[0]);}Collections.sort(definitions);c.derived.put("sccDefinitionReferences",definitionKnown?definitions:null);
  c.add("scc-definition-collection","SCC","3.302(1)(b)","P244–246",definitionKnown?"amend":"pending",definitionKnown?definitions:null,"List only actually adopted SCC1 definitions; preserve following unrelated SCC3/5 references.","仅列实际采用SCC1定义，保留后续无关SCC3／5引用。","pricingScheme","allBqQuantitiesProvisional","oldValuableTrees","excavationPermitRequired","targetOverrides");
  c.add("scc-technical-proposal-reference","SCC","1.301","P100–114",standardStructure?"amend":"pending",standardStructure?map("envelope","1","submissionClause","SCT5(3)"):null,customStructure?"The adopted whole SCT5 procedure has an unverified final submission structure. Adopt the exact SCC1.301 Technical Proposals definition referencing the final submission clause; the original definition is preserved.":"Use the adopted technical-envelope and final submission-clause position. A custom system does not delete Contract / Letter of Acceptance definitions.",customStructure?"整条采用SCT5后，最终提交结构尚未核实。请在SCC1.301技术建议定义目标采用引用最终提交条号的准确改文；原定义保留。":"采用实际技术信封及最终提交条号；其他制度不删除Contract／Letter of Acceptance定义。","twoEnvelopeTendering","otherTenderingArrangement","targetOverrides");
  if(customStructure)c.a("scc-technical-proposal-reference").put("pendingKind","FinalStructure");
  String training=s(c.a("scc-demolition-training").get("action"));String late=s(c.a("scc-late-possession").get("action"));c.add("scc-training-numbering","SCC","8.308","P937–951",Arrays.asList("not_adopted","delete","not_used").contains(training)?"not_adopted":"pending".equals(training)||"pending".equals(late)?"pending":"amend",Arrays.asList("retain","amend").contains(late)?"(3)/(4)→(5)/(6); 8.2(3)→8.2(5)":"standard numbering","Numbering follows actual 8.301 adoption, independently of Section count.","编号跟随实际8.301采用，与Section数量无关。","latePossessionAdopted","policeTrainingAdopted","targetOverrides");
 }
 static List<Map<String,Object>> requirements(Map<String,Object> v){LinkedHashMap<String,Map<String,Object>> result=new LinkedHashMap<>();for(String field:Arrays.asList("additionalSubmissions","pseSubmissions")){if("pseSubmissions".equals(field)&&!Boolean.TRUE.equals(and(truth(v.get("domesticBlocks")),truth(v.get("volumetricPrecastComponents")))))continue;for(Object o:list(v.get(field))){String t=o instanceof String?s(o):s(asMap(o).get("text"));if(!answered(t))continue;String key=t.trim().replaceAll("\\s+"," ");Map<String,Object> row=result.get(key);if(row==null){row=map("text",t,"sources",new ArrayList<String>());result.put(key,row);}list(row.get("sources")).add(field);}}return new ArrayList<>(result.values());}
 static void adoptTargetEdits(Context c,Object raw){for(Object o:list(raw)){Map<String,Object>edit=asMap(o);String id=s(edit.get("actionId"));Map<String,Object>a=c.find(id);if(a==null)continue;String action=s(edit.get("action"));if(DraftTargetDecisions.problem(a,edit)!=null)continue;Object text=DraftTargetDecisions.text(edit);
  if("SourceCheck".equals(a.get("pendingKind")))a.putIfAbsent("sourceWarning",a.get("detail"));a.put("action",action);if(answered(text))a.put("value",text);else a.remove("value");a.put("manual",true);a.put("sourceMapping",edit.get("sourceMapping"));a.put("detail",copy("The business user's exact target decision applies for this draft. Original source / edition warnings remain recorded.","业务用户准确目标决定仅用于本次起草；原来源／版次告警保留。"));Set<Object> relatedKeys=new LinkedHashSet<>(list(a.get("inputKeys")));relatedKeys.add("targetOverrides");a.put("inputKeys",new ArrayList<>(relatedKeys));}}
 public static Map<String,Object> map(Object... pairs){Map<String,Object> r=new LinkedHashMap<>();for(int i=0;i<pairs.length;i+=2)r.put(String.valueOf(pairs[i]),pairs[i+1]);return r;}
 public static Map<String,Object> copy(String en,String zh){return map("en",en,"zhHans",zh,"zhHant",traditional(zh));}
 public static String traditional(String zh){String from="办报备币编变标别补测层产偿场称迟冲础处触纯词辞从达单担当档导递点电调叠订动独断对额发费风负复该盖个给构关规还号户护话环缓换汇会机积辑计记际价间检见键将脚阶节结仅进经静旧据决开槛库来览乐类离连联练两楼录码没门纳难内拟盘评凭气签墙请区权确认赛删设审声师时实视适书输属术树数双说随损缩台态题体条铁图网围卫为谓问无务细现项协写须虚许续选询训压验养样业页遗义议异应营于与语预约阅暂则择责这证职纸质终种铸专砖桩装状准资总组";
  String to  ="辦報備幣編變標別補測層產償場稱遲沖礎處觸純詞辭從達單擔當檔導遞點電調疊訂動獨斷對額發費風負復該蓋個給構關規還號戶護話環緩換匯會機積輯計記際價間檢見鍵將腳階節結僅進經靜舊據決開檻庫來覽樂類離連聯練兩樓錄碼沒門納難內擬盤評憑氣簽墻請區權確認賽刪設審聲師時實視適書輸屬術樹數雙說隨損縮臺態題體條鐵圖網圍衛為謂問無務細現項協寫須虛許續選詢訓壓驗養樣業頁遺義議異應營於與語預約閱暫則擇責這證職紙質終種鑄專磚樁裝狀準資總組";
  StringBuilder out=new StringBuilder();for(char ch:zh.toCharArray()){int i=from.indexOf(ch);out.append(i>=0&&i<to.length()?to.charAt(i):ch);}return out.toString();}
 static Map<String,Object> issue(String id,String kind,String document,String clause,List<String>keys,String msg){String zh="请核对本次采用输入及来源；已输入内容保留供修改。";String key=keys.isEmpty()?"":keys.get(0);if("InputMissing".equals(kind))zh="请补填或采用本次起草的输入值；未知不等于否，已填的其他值保留。";else if("PrerequisiteUnknown".equals(kind))zh="前置事实尚未确定；本字段仍可填写，未知不等于否。";else if("InputConflict".equals(kind))zh="本次采用的39个月判定与记录工期不一致；保留人工采用判定，并标记待复核。";else if("InvalidOverride".equals(kind))zh="目标修改无效：请核对目标编号、动作及准确采用改文；无效内容不会应用。";else if("InputInvalid".equals(kind)){if(key.startsWith("siteInspection"))zh="请填写有效的ISO日期，并确认开始日期不晚于结束日期；原输入保留。";else if(key.startsWith("advanceRepayment"))zh="还款月数及首期付款证书编号须为正整数；原输入保留，不采用零、负数或小数。";else if(key.equals("billNos"))zh="请补全每行Bill／Schedule编号及准确说明，并核对同一计价类型内重复编号；原行保留。";else if(key.equals("oldValuableTrees"))zh="请补全并核对每株古树编号；缺号或重复行不会视为更多树木，原行保留。";else if(key.equals("sections"))zh="每个Section须有独立编号及实际工程类型；请核对重复或缺项，原行保留。";else if(DraftBlueprint.find(key)!=null&&"list".equals(DraftBlueprint.find(key).kind))zh="请补全每行必要字段并核对有效选项；原行保留供修改，不会用于本次生成。";else zh="请输入有限、非负的有效数值；无效原输入保留供复核。";}return map("id",id,"kind",kind,"document",document,"clause",clause,"inputKeys",keys,"message",copy(msg,zh));}
 @SuppressWarnings("unchecked") public static Map<String,Object> asMap(Object o){return o instanceof Map?(Map<String,Object>)o:Collections.emptyMap();}
 @SuppressWarnings("unchecked") public static List<Object> list(Object o){return o instanceof List?(List<Object>)o:Collections.emptyList();}
 static String s(Object o){return o==null?"":String.valueOf(o);}
 static String join(Collection<?>list){StringJoiner out=new StringJoiner(", ");for(Object o:list)out.add(s(o));return out.toString();}
 static class Context {
  final Map<String,Object>v,derived=new LinkedHashMap<>();final List<Map<String,Object>>actions;Context(Map<String,Object>v,List<Map<String,Object>>a){this.v=v;actions=a;}
  Boolean b(String key){return truth(v.get(key));}String str(String key){return s(v.get(key));}boolean has(String...keys){for(String key:keys)if(!answered(v.get(key)))return false;return true;}
  Map<String,Object>find(String id){for(Map<String,Object>a:actions)if(id.equals(a.get("id")))return a;return null;}Map<String,Object>a(String id){Map<String,Object>r=find(id);if(r==null)throw new IllegalArgumentException("Unknown drafting action "+id);return r;}
  void set(String id,String action,Object value,String en,String zh,String...keys){Map<String,Object>r=a(id);r.put("action",action);r.put("inputKeys",Arrays.asList(keys));r.put("detail",copy(en,zh));if(value!=null)r.put("value",value);else r.remove("value");}
  void source(String id,String en,String zh,String...keys){set(id,"pending",null,en,zh,keys);a(id).put("pendingKind","SourceCheck");}
  void add(String id,String doc,String clause,String paragraphs,String action,Object value,String en,String zh,String...keys){if(find(id)==null)actions.add(map("id",id,"document",doc,"clause",clause.startsWith(doc)?clause:doc+clause,"paragraphs",paragraphs));set(id,action,value,en,zh,keys);}
 }
}
