package com.consense.service.drafting;

import com.consense.common.BizException;
import com.consense.domain.Project;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType0Font;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * 起草文稿 PDF 预览（PDFBox 直接绘制，A4）。
 * 第 3 步「审阅模式 / 最终预览」用浏览器原生 PDF 渲染，与审查报告同一套字体与分页策略。
 */
@Slf4j
@Component
public class DraftDocPdfWriter {

    private static final float PAGE_W = PDRectangle.A4.getWidth();
    private static final float PAGE_H = PDRectangle.A4.getHeight();
    private static final float MARGIN = 56f;
    private static final float BODY_SIZE = 10.5f;
    private static final float LINE_GAP = 5.2f;
    private static final float CONTENT_W = PAGE_W - MARGIN * 2;

    public byte[] write(Project project, String fileKey, String title, String markdown) {
        try (PDDocument document = new PDDocument()) {
            PDFont font = loadFont(document);
            Cursor cursor = new Cursor(document, font);

            drawHead(cursor, project, fileKey, title);
            cursor.y -= 10;
            if (markdown != null && !markdown.trim().isEmpty()) {
                drawBody(cursor, markdown);
            } else {
                cursor.text(BODY_SIZE, "(empty content)", false);
            }
            drawFooters(cursor, fileKey);
            cursor.close();

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            document.save(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new BizException(4100, "生成文稿 PDF 失败: " + e.getMessage());
        }
    }

    // ------------------------------------------------------------------ 头部与页脚

    private void drawHead(Cursor cursor, Project project, String fileKey, String title) throws IOException {
        // 顶部色带
        cursor.stream().setNonStrokingColor(0.06f, 0.24f, 0.36f);
        cursor.stream().addRect(0, PAGE_H - 96, PAGE_W, 96);
        cursor.stream().fill();

        cursor.y = PAGE_H - 38;
        cursor.textWhite(16, nvl(title));
        cursor.y -= 20;
        String meta = fileKey + " · Contract No.: " + nvl(project.getContractNo())
                + (isBlank(project.getPackageRef()) ? "" : " · Package Ref.: " + nvl(project.getPackageRef()));
        cursor.textWhite(9, meta);
        cursor.y -= 16;
        cursor.textWhite(8.5f, LocalDate.now().format(DateTimeFormatter.ISO_LOCAL_DATE)
                + " · Generated by ConSense CAC Solution");
        cursor.y = PAGE_H - 118;
    }

    private void drawFooters(Cursor cursor, String fileKey) throws IOException {
        int total = cursor.pageCount();
        for (int i = 0; i < total; i++) {
            PDPageContentStream stream = new PDPageContentStream(cursor.document(), cursor.page(i), true, true);
            stream.setStrokingColor(0.85f, 0.87f, 0.89f);
            stream.moveTo(MARGIN, 40);
            stream.lineTo(PAGE_W - MARGIN, 40);
            stream.stroke();
            stream.beginText();
            stream.setFont(cursor.font(), 8f);
            stream.setNonStrokingColor(0.55f, 0.58f, 0.62f);
            stream.newLineAtOffset(MARGIN, 28);
            stream.showText("ConSense · " + fileKey);
            stream.endText();
            stream.beginText();
            stream.setFont(cursor.font(), 8f);
            stream.newLineAtOffset(PAGE_W - MARGIN - 30, 28);
            stream.showText((i + 1) + " / " + total);
            stream.endText();
            stream.close();
        }
    }

    // ------------------------------------------------------------------ 正文（简化 Markdown）

    private void drawBody(Cursor cursor, String markdown) throws IOException {
        boolean inList = false;
        for (String raw : markdown.replace("\r\n", "\n").split("\n")) {
            String line = raw.replaceAll("\\s+$", "");

            if (line.trim().isEmpty()) {
                inList = false;
                cursor.y -= 6;
                continue;
            }
            if (line.startsWith("---") && line.replace("-", "").trim().isEmpty()) {
                inList = false;
                cursor.ensure(14);
                cursor.stream().setStrokingColor(0.82f, 0.84f, 0.87f);
                cursor.stream().moveTo(MARGIN, cursor.y - 6);
                cursor.stream().lineTo(PAGE_W - MARGIN, cursor.y - 6);
                cursor.stream().stroke();
                cursor.y -= 16;
                continue;
            }
            if (line.startsWith("### ")) {
                inList = false;
                cursor.y -= 6;
                cursor.text(11.5f, clean(line.substring(4)), true);
                cursor.y -= 3;
                continue;
            }
            if (line.startsWith("## ")) {
                inList = false;
                cursor.y -= 8;
                cursor.text(13f, clean(line.substring(3)), true);
                cursor.y -= 4;
                continue;
            }
            if (line.startsWith("# ")) {
                inList = false;
                cursor.y -= 10;
                cursor.text(15.5f, clean(line.substring(2)), true);
                cursor.y -= 5;
                continue;
            }
            if (line.startsWith("> ")) {
                inList = false;
                cursor.y -= 2;
                List<String> lines = cursor.wrap(clean(line.substring(2)), BODY_SIZE, CONTENT_W - 14);
                for (String l : lines) {
                    cursor.ensure(BODY_SIZE + LINE_GAP);
                    cursor.stream().setNonStrokingColor(0.92f, 0.93f, 0.95f);
                    cursor.stream().addRect(MARGIN, cursor.y - BODY_SIZE - 3, CONTENT_W, BODY_SIZE + 6);
                    cursor.stream().fill();
                    cursor.textAt(MARGIN + 7, cursor.y - BODY_SIZE, BODY_SIZE, l, false, false);
                    cursor.y -= BODY_SIZE + LINE_GAP;
                }
                cursor.y -= 4;
                continue;
            }
            if (line.startsWith("- ") || line.startsWith("* ")) {
                if (!inList) {
                    cursor.y -= 3;
                    inList = true;
                }
                List<String> lines = cursor.wrap(clean(line.substring(2)), BODY_SIZE, CONTENT_W - 16);
                for (int i = 0; i < lines.size(); i++) {
                    cursor.ensure(BODY_SIZE + LINE_GAP);
                    if (i == 0) {
                        cursor.stream().setNonStrokingColor(0.094f, 0.365f, 0.647f);
                        cursor.stream().addRect(MARGIN + 3, cursor.y - BODY_SIZE + 1, 3.2f, 3.2f);
                        cursor.stream().fill();
                    }
                    cursor.textAt(MARGIN + 14, cursor.y - BODY_SIZE, BODY_SIZE, lines.get(i), false, false);
                    cursor.y -= BODY_SIZE + LINE_GAP;
                }
                continue;
            }
            // 普通段落
            inList = false;
            for (String l : cursor.wrap(clean(line), BODY_SIZE, CONTENT_W)) {
                cursor.text(BODY_SIZE, l, false);
            }
            cursor.y -= 4;
        }
    }

    /** 去掉 Markdown 行内标记（**加粗**、`code`），PDF 里统一按普通文本绘制 */
    private String clean(String text) {
        return text.replace("**", "").replace("`", "");
    }

    private String nvl(String value) {
        return value == null ? "" : value;
    }

    private boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }

    /**
     * 中文字体：与 VettingPdfWriter 同策略，Windows 自带 simhei/simsun/msyh，退回 Helvetica。
     */
    private PDFont loadFont(PDDocument document) {
        for (String path : new String[]{
                "C:/Windows/Fonts/simhei.ttf",
                "C:/Windows/Fonts/simsun.ttc",
                "C:/Windows/Fonts/msyh.ttc"}) {
            File file = new File(path);
            if (file.exists() && path.endsWith(".ttf")) {
                try {
                    return PDType0Font.load(document, file);
                } catch (IOException e) {
                    log.warn("加载字体 {} 失败: {}", path, e.getMessage());
                }
            }
        }
        try {
            return PDType0Font.load(document, new File("C:/Windows/Fonts/simkai.ttf"));
        } catch (Exception ignored) {
            log.warn("未找到可用中文字体，PDF 中文可能缺字");
        }
        return PDType1Font.HELVETICA;
    }

    /** 分页与文字绘制游标（与 VettingPdfWriter 保持一致的绘制语义） */
    private static final class Cursor {

        private final PDDocument document;
        private final PDFont font;
        private final PDFont latinFont;
        private final java.util.Map<Integer, PDFont> glyphFonts = new java.util.HashMap<>();
        private final List<PDPage> pages = new ArrayList<>();
        private PDPageContentStream stream;
        private float y;

        Cursor(PDDocument document, PDFont font) throws IOException {
            this.document = document;
            this.font = font;
            File latin = new File("C:/Windows/Fonts/arial.ttf");
            this.latinFont = latin.exists() ? PDType0Font.load(document, latin) : PDType1Font.HELVETICA;
            newPage();
        }

        PDDocument document() {
            return document;
        }

        PDFont font() {
            return font;
        }

        PDPage page(int index) {
            return pages.get(index);
        }

        int pageCount() {
            return pages.size();
        }

        PDPageContentStream stream() {
            return stream;
        }

        void newPage() throws IOException {
            if (stream != null) {
                stream.close();
            }
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            pages.add(page);
            stream = new PDPageContentStream(document, page);
            y = PAGE_H - MARGIN;
        }

        void ensure(float needed) throws IOException {
            if (y - needed < MARGIN + 30) {
                newPage();
            }
        }

        void text(float size, String value, boolean bold) throws IOException {
            ensure(size + LINE_GAP);
            y -= size;
            textAt(MARGIN, y, size, value, bold, false);
            y -= LINE_GAP;
        }

        void textWhite(float size, String value) throws IOException {
            textAt(MARGIN, y, size, value, true, true);
        }

        void textAt(float x, float baseline, float size, String value, boolean bold, boolean white) throws IOException {
            stream.beginText();
            stream.setFont(font, size);
            if (white) {
                stream.setNonStrokingColor(1f, 1f, 1f);
            } else if (bold) {
                stream.setNonStrokingColor(0.094f, 0.133f, 0.188f);
            } else {
                stream.setNonStrokingColor(0.29f, 0.31f, 0.35f);
            }
            stream.newLineAtOffset(x, baseline);
            PDFont active = null;
            StringBuilder run = new StringBuilder();
            for (int point : sanitize(value).codePoints().toArray()) {
                PDFont selected = fontFor(point);
                if (active != null && selected != active) {
                    stream.setFont(active, size);
                    stream.showText(run.toString());
                    run.setLength(0);
                }
                active = selected;
                run.appendCodePoint(point);
            }
            if (active != null) {
                stream.setFont(active, size);
                stream.showText(run.toString());
            }
            stream.endText();
        }

        List<String> wrap(String text, float size, float maxWidth) {
            List<String> lines = new ArrayList<>();
            if (text == null || text.trim().isEmpty()) {
                return lines;
            }
            for (String paragraph : text.split("\n")) {
                StringBuilder current = new StringBuilder();
                float currentWidth = 0;
                for (int point : sanitize(paragraph).codePoints().toArray()) {
                    String character = new String(Character.toChars(point));
                    float characterWidth = width(character, size);
                    if (current.length() > 0 && currentWidth + characterWidth > maxWidth) {
                        int boundary = current.lastIndexOf(" ");
                        if (boundary > 0 && point < 0x2e80 && !Character.isWhitespace(point)) {
                            lines.add(current.substring(0, boundary));
                            String remainder = current.substring(boundary + 1);
                            current.setLength(0);
                            current.append(remainder);
                            currentWidth = width(remainder, size);
                        } else {
                            lines.add(current.toString().stripTrailing());
                            current.setLength(0);
                            currentWidth = 0;
                        }
                    }
                    if (current.length() == 0 && Character.isWhitespace(point)) continue;
                    current.append(character);
                    currentWidth += characterWidth;
                }
                lines.add(current.toString());
            }
            return lines;
        }

        private float width(String text, float size) {
            try {
                float total = 0;
                for (int point : sanitize(text).codePoints().toArray())
                    total += fontFor(point).getStringWidth(new String(Character.toChars(point))) / 1000 * size;
                return total;
            } catch (IOException e) {
                return text.length() * size * 0.5f;
            }
        }

        private PDFont fontFor(int point) {
            return glyphFonts.computeIfAbsent(point, value -> {
                String character = new String(Character.toChars(value));
                PDFont first = value < 0x2e80 ? latinFont : font;
                PDFont second = first == font ? latinFont : font;
                for (PDFont candidate : new PDFont[]{first, second}) {
                    try { candidate.encode(character); return candidate; }
                    catch (IllegalArgumentException | IOException unavailable) { }
                }
                throw new BizException(4100, "PDF字体不支持字符 U+" + Integer.toHexString(value).toUpperCase());
            });
        }

        private String sanitize(String text) {
            if (text == null) {
                return "";
            }
            StringBuilder builder = new StringBuilder(text.length());
            for (char c : text.toCharArray()) {
                if (c < 0x20 && c != '\n') {
                    continue;
                }
                builder.append(c);
            }
            return builder.toString();
        }

        void close() throws IOException {
            if (stream != null) {
                stream.close();
            }
        }
    }
}
